### ISSUE TITLE
Name the terminals

### ISSUE THREAD

**Issue by JostCrow** [jeremyramin/terminal-plus#10]
Could it be possible to name the terminals so it will be possible to see what they are doing?

![screenshot from 2015-09-16 11 41 53](https://cloud.githubusercontent.com/assets/390575/9901615/014de290-5c69-11e5-954e-dfdaa07ecc4f.png)

**Comment by jeremyramin** [comment]
@JostCrow That could be possible. What is the best way to implement this? Right click menu and then present a modal for entering a name?

**Comment by JostCrow** [comment]
Yes I would do something like that. That way you don't have to name them.

**Comment by jeremyramin** [comment]
I'll look into adding this and get back to you once I have published it.

**Comment by jeremyramin** [comment]
Added in latest release ([v0.5.0](https://github.com/jeremyramin/terminal-plus/commit/48566fec628e8132989203226e490458be7fe43a)).

**Comment by JostCrow** [comment]
Thanks it looks great
