### ISSUE TITLE
Using 'clear' and 'reset' commands

### ISSUE THREAD

**Issue by nunocastromartins** [jeremyramin/terminal-plus#101]
The cursor disappears when using `clear`/`reset` commands from a terminal window until certain keys (e.g. backspace or arrow keys) are pressed or the terminal window is refocused.

Also, when using `clear` I can't seem to scroll back up. I don't think that's the expected behaviour.

Keep up with the good work! :smile:

**Comment by jeremyramin** [comment]
Fixed by v0.14.4. Please remember to close this thread if your issue has been resolved.

**Comment by nunocastromartins** [comment]
I don't think that this is completely resolved.
The problem with the missing cursor and the clearing of history are gone.

The `clear` command, however, still behaves differently from the system's terminal (at least in my system, not sure whether this can be different in other systems).
Specifically, using `clear` in the system's terminal doesn't output any new lines, meaning that scrolling up only scrolls "one line". In terminal-plus, multiple new lines are output.

I don't consider this a major issue, it's just different so I thought I'd mention it. If you don't consider this an issue then I'll close the thread. :smile:

If I didn't explain myself properly please do say so and I'll post a picture of what I mean.

**Comment by jeremyramin** [comment]
I think I understand what you mean but a picture would be nice. Thanks.

**Comment by nunocastromartins** [comment]
System's terminal, after using `clear` and scrolling up:
![gnome-terminal](https://cloud.githubusercontent.com/assets/8314616/11369751/7740c60e-92b8-11e5-9787-f8d5d626540b.jpg)

Atom's terminal-plus, after using `clear` and scrolling up (I also resized the window by one line so that the last line is shown):
![atom-terminal](https://cloud.githubusercontent.com/assets/8314616/11369749/773ed768-92b8-11e5-8b3e-6505fbc44f4c.png)

**Comment by jeremyramin** [comment]
Noted. I will make adjustments for the next release.

**Comment by jeremyramin** [comment]
I believe I have fixed it in the latest release. Please let me know what you think.

**Comment by nunocastromartins** [comment]
This is solved, as far as I'm concerned. :-)
