### ISSUE TITLE
Option to open as a tab

### ISSUE THREAD

**Issue by ywecur** [jeremyramin/terminal-plus#103]
Currently it's only possible to open as a pull-down. It would be great to always have a dedicated terminal tab open!

**Comment by ywecur** [comment]
[This code might help](https://github.com/Floobits/atom-term3/blob/master/lib/term-view.coffee)

**Comment by jeremyramin** [comment]
If you drag the status icon up to the atom tab bar, it will become a tab. This tab mode is experimental though as I'm still testing it and finding issues. It should work for most purposes.

**Comment by jeremyramin** [comment]
Please remember to close this issue if it has been resolved.

**Comment by ywecur** [comment]
@jeremyramin Of course, sorry.
