### ISSUE TITLE
Default panel height as a percentage

### ISSUE THREAD

**Issue by tonatiuh** [jeremyramin/terminal-plus#104]
IMO it would be nice if the terminal height could be set not only as a fixed number but also as a percentage of the screen height.

**Comment by pmsm1100** [comment]
+1

**Comment by jeremyramin** [comment]
I will try adding this and get back to you.

**Comment by jeremyramin** [comment]
Added in v0.14.4. Please remember to close this thread if your issue has been resolved.

**Comment by tonatiuh** [comment]
Awesome @jeremyramin! Nice job!
