### ISSUE TITLE
Option for font size?

### ISSUE THREAD

**Issue by freakypie** [jeremyramin/terminal-plus#105]
It would be nice if we could choose the font size for the terminals.

**Comment by jeremyramin** [comment]
The terminal should match Atom's font size. I can include a font size override in the settings though.

**Comment by freakypie** [comment]
The difference between the terminal and editors was the font family, and it made the terminal appear larger. I think it would be good to have a customizable size.

**Comment by jeremyramin** [comment]
Noted. Expect it in the next release.

**Comment by jeremyramin** [comment]
Resolved by v0.14.4. Please remember to close this thread if your issue has been resolved.

**Comment by freakypie** [comment]
:cake:
