### ISSUE TITLE
Can't copy command line.

### ISSUE THREAD

**Issue by luunguyenbk** [jeremyramin/terminal-plus#107]
Hi developers!

I have a issue with copy lines, when i use mouse to select which lines i want and press "CMD + C" ( MacOS), the selected highlight is disappear, so that can't let me to copy. I must to use right click and select copy, it is a little bit disagreeable.

Can you improve this functions.

Thanks you!

**Comment by jeremyramin** [comment]
I know what is causing this. I'll fix this and let you know when the next release is out.

**Comment by smnbbrv** [comment]
+1, please fix it as soon as you can, this really slows down the working process

**Comment by jeremyramin** [comment]
My apologies, I will get right on it.

**Comment by jeremyramin** [comment]
Fixed as of v0.14.5. Review the changes and let me know if your issue has been properly fixed. If your issue has been resolved, please close this issue thread.

**Comment by luunguyenbk** [comment]
It's working perfect now, thanks you !

**Comment by smnbbrv** [comment]
works like a charm and is fixed so fast! Thank you very much :)
