### ISSUE TITLE
Windows - Atom 1.0.11 OK - Atom 1.0.13 Not working

### ISSUE THREAD

**Issue by JohnMurga** [jeremyramin/terminal-plus#11]
Hey,

Awesome Package :-)

Anyway, doesn't work on 1.0.13 as I am assuming that the native pty.js module would have to be rebuilt for IO.js 2.3.1 ... Ironically Atom says that it rebuilt it, but then it still doesn't work.

Thanks !!

**Comment by jeremyramin** [comment]
@JohnMurga Thanks for letting me know. I really need to find a better way to handle the pty.js dependency but I don't have any ideas. I can rebuild for atom 1.0.13 but I think then the people who haven't updated will get an issue.

**Comment by JohnMurga** [comment]
I suspect 1.0.12 is affected too, as that's the one where IO.js and Electron got the update

**Comment by jeremyramin** [comment]
Please try updating the Terminal-Plus dependencies. If you are not familiar with this process you can uninstall and reinstall the package. Pty.js has been rebuilt and should work now.

**Comment by JohnMurga** [comment]
Wow, that was fast :-)
Thanks !!
Will try in a few hours

**Comment by jeremyramin** [comment]
Did this work for you?

**Comment by JohnMurga** [comment]
Sorry ...
Yeah, works beautifully :+1: 
Thanks !!
