### ISSUE TITLE
Tree view and git gutter do not update after git commands are executed.

### ISSUE THREAD

**Issue by KenPowers** [jeremyramin/terminal-plus#111]
Whenever I execute git commands in the terminal the tree view and git gutter don't update:

![image](https://cloud.githubusercontent.com/assets/174864/11434498/8039c9b0-949b-11e5-8e4e-b31cb9ea70a9.png)

The tree view should be all the same color and the git gutter shouldn't have any colors. Blurring and focussing the Atom window fixes the issue.

**Comment by KenPowers** [comment]
Also, since it's pointed out in the `README`, the available updates are UI theme related:

![image](https://cloud.githubusercontent.com/assets/174864/11434544/0ec11c56-949c-11e5-91ea-ed26cc7ec17f.png)

**Comment by jeremyramin** [comment]
Terminal-Plus has no influence over the git-gutter and tree-view. Those views are run by their own packages that are a part of Atom.

**Comment by KenPowers** [comment]
I figured as much. It would be great if there was a way for the terminal to notify Atom to check for updates after certain commands (or all commands, if that isn't excessive).

**Comment by jeremyramin** [comment]
Unfortunately there is no way for Terminal-Plus to know when you are entering a command. It simply takes your keypresses and passes them along to your shell.

**Comment by KenPowers** [comment]
Hm. That's unfortunate.
