### ISSUE TITLE
Cut and Paste not working with hotkeys on Mac

### ISSUE THREAD

**Issue by ksnyde** [jeremyramin/terminal-plus#113]
In more recent builds of the terminal package I am no longer able to use the CMD-C and CMD-V cut and paste operations. I have demonstrated this here:

> [video link](https://vimeo.com/147125881)

**Comment by jeremyramin** [comment]
Yes, this was an issue before v0.14.5. Please update to this latest version and reload Atom for the changes to take effect.

**Comment by ksnyde** [comment]
ok, i had updated but I guess the change took hold only after I restarted Atom.
