### ISSUE TITLE
'terminal-plus:toggle'

### ISSUE THREAD

**Issue by tobiasbueschel** [jeremyramin/terminal-plus#115]
I created a custom shortcut to toggle the terminal

'.platform-darwin atom-workspace':
  'ctrl-esc': 'terminal-plus:toggle'

However, once it appears it does not hide when 'ctrl-esc' is pressed again.

**Comment by jeremyramin** [comment]
`ctrl-esc` is an escape sequence that is recognized by Terminal-Plus. The terminal intercepts the keydown event before Atom can respond to it. This is how the terminal prevents other common sequences for terminals (like `control-c`) from being triggered as Atom keydown events. I am sorry for the inconvenience, but you will have to pick something else.

**Comment by tobiasbueschel** [comment]
thanks for the swift reply @jeremyramin! I changed it to ```ctrl-.``` and it works great! Cheers :+1:
