### ISSUE TITLE
Git Bash opens in new window on Windows

### ISSUE THREAD

**Issue by matthewcanty** [jeremyramin/terminal-plus#117]
The default terminal is Powershell, but I want it to be Git Bash.

I have set Shell Override to C:\Program Files\Git\git-bash.exe but this opens in a new window.

![image](https://cloud.githubusercontent.com/assets/2089581/11558244/7401f286-99a9-11e5-86d4-174d0407381a.png)

**Comment by matthewcanty** [comment]
Shell Override: C:\Program Files\Git\bin\sh.exe
Shell Arguments: --login

**Comment by jeremyramin** [comment]
I was curious as to how some people got git bash running in Terminal-Plus on Windows, so thanks for this!

I'm glad that you were able to resolve your issue. Thank you for using Terminal-Plus.

**Comment by matthewcanty** [comment]
It's great. Although I'm having an issue which is preventing me from using it. As I type and hit backspace and move about the command line, weird things happen. Characters move around and things get displaced. Some characters but unpassable and undeletable.

The only resolution is to hit enter - Esc or Ctrl+C do not work. 

Not sure if this is your problem or a problem with Powershell and Git Bash Shell...

**Comment by matthewcanty** [comment]
Just tried it in normal Powershell, no issues there.

I tried to capture a screen recording but Recordit was having trouble with my resolution I think... Will try again in the morning.

**Comment by jeremyramin** [comment]
I'll have to test this myself when I have time. The recording you mentioned would be nice so I can see exactly what is going wrong.

**Comment by matthewcanty** [comment]
![weird-atom-terminal-issue](https://cloud.githubusercontent.com/assets/2089581/11588761/d6b3ddc8-9a7a-11e5-8bff-e60c5860c258.gif)

See how all the text is being rearranged. Soon after the clip starts, a can't traverse back past _a_...

**Comment by jeremyramin** [comment]
Thanks for the animation, I see what is happening now. Unfortunately I won't have time to test this myself until next week. Sorry for the inconvenience. I'll be sure to let you know once I have tested this and fixed it.

**Comment by Severance** [comment]
Hi @jeremyramin, I was wondering if you've made any progress sorting this out for Git Bash; I'd love to make use of it but it's impossible to with this backspace bug.

**Comment by savbace** [comment]
have same issue with git bash as @matthewcanty has

**Comment by ibnuh** [comment]
Hi @jeremyramin I'm still having the same issue with git bash as @mattcanty has in 2017, please fix it. Please
