### ISSUE TITLE
Terminal freezes

### ISSUE THREAD

**Issue by ardit700** [jeremyramin/terminal-plus#122]
Hi Jeremy

I am using terminal-plus on Windows 7 with the latest Atom stable release.

The terminal seems to freeze once I open it. It doesn't show the directory path and doesn't let you type anything inside it.

I tried to uninstall it and install it again. Once I reinstall it, the terminal seems to open correctly and let's you write for a few seconds, and then freezes again.

Here is the issue report if that can help:

**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at Task.module.exports.Task.send (C:\Users\adi\AppData\Local\atom\app-1.2.4\resources\app.asar\src\task.js:117:27)
    at TerminalPlusView.module.exports.TerminalPlusView.input (file:///C:/Users/adi/.atom/packages/terminal-plus/lib/view.coffee:261:17)
    at Terminal.<anonymous> (file:///C:/Users/adi/.atom/packages/terminal-plus/lib/view.coffee:141:8)
    at Terminal.EventEmitter.emit (C:\Users\adi\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\adi\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\adi\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:3253:12
```

### Commands

```
     -4:30.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "repl-term",
      "rhino-python",
      "script-runner",
      "python-terminal"
    ]
  },
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
This means that something is closing the agent that runs your shell in the background. Please make sure that `winpty-agent.exe` is not being closed by any of your programs. If you have antivirus, that would be a good place to start and check.

**Comment by ardit700** [comment]
Thanks Jeremy. I found out winpty-agent.exe was part of the Pycharm and Android Studio installations. I uninstalled both those software, and reinstalled Atom and terminal-plus but I still get the same error. There doesn't seem to be a winpty-agent.exe file anymore in my computer. And I don't have an antivirus. 

If you have any further tips on troubleshooting this, please let me know.
Ardit.

**Comment by ardit700** [comment]
Alright, there seemed to be a virus in my WIndows installation that affected access permission. Basically, some files could not be modified while various software tried to make changes.
I installed a fresh Windows 7 and it is now working again.
Thanks for your assistance Jeremy.

**Comment by jeremyramin** [comment]
Sorry for the late reply. I'm glad you were able to find a solution to this.
