### ISSUE TITLE
Character corruption has occured when type multibyte characters

### ISSUE THREAD

**Issue by Mathahal** [jeremyramin/terminal-plus#128]
when I typed some japanese characters, it occured.
it is not available with multibyte characters typing?
![screen shot 2015-12-11 at 18 29 19](https://cloud.githubusercontent.com/assets/5163255/11740336/23c5e4d4-a035-11e5-812a-6a111a8bec5e.png)

thank you.

**Comment by jeremyramin** [comment]
Other users and I have been able to type Japanese characters. The things to consider here are:
1. Which operating system are you running on?
2. What font do you have set for Atom and Terminal-Plus?
3. Which shell are you using?

**Comment by Mathahal** [comment]
Thank you for replying,

1. Which operating system are you running on?
> OSX 10.9.5 
2. What font do you have set for Atom and Terminal-Plus?
> Myrica M
3. Which shell are you using?
> zsh 5.0.2

**Comment by jeremyramin** [comment]
Were you using a certain command line application while this was happening?

**Comment by Mathahal** [comment]
It turned 'あ' into '<00e3><0081><0082>' whereever I typed on Shell<br>and<br>turned 'あ' into '�~A~B' where I typed on Vim.

**Comment by Mathahal** [comment]
I tried to change language settings in OSX System Preferences from English to Japanese, then It has fixed.
Thank you so much.

**Comment by jeremyramin** [comment]
I'm glad you were able to solve your issue. Thank you for using Terminal-Plus.
