### ISSUE TITLE
decreased performance when running python script

### ISSUE THREAD

**Issue by am-webdev** [jeremyramin/terminal-plus#13]
Running a Python script in nativ terminal is super fast but if I run the same script from terminal-plus it takes much more time and also Atom is lagging and can not be used until the script is finished or aborted. So the whole package becomes useless for me :(

using atom 1.0.11 on osx 10.10.5 and terminal-plus 0.4.2

**Comment by jeremyramin** [comment]
I'll add this to the list of improvements and get back to you once I release a solution.

**Comment by jeremyramin** [comment]
Could you provide me with an example script I could test this with? I tried doing a python script as well as a terminal stress test and found no issues. Atom was responsive and the task completed in the same amount of time as usual.

**Comment by jeremyramin** [comment]
Closing this issue since I haven't seen or heard of any performance issues.
