### ISSUE TITLE
How to change the position of the terminal pane

### ISSUE THREAD

**Issue by onGstring** [jeremyramin/terminal-plus#141]
Hello! The terminal pane is fixed in the below of the window. How to move it to the side of the window?  Thanks :-)

**Comment by jeremyramin** [comment]
Right now there is an experimental feature that allows you to make the panel a tab. Please try dragging the status-icon to Atom's tab-bar to turn it into a tab. You could then split your pane and put the terminal on the right while a text editor sits on the left.

**Comment by onGstring** [comment]
It works! Thanks :-)

**Comment by ashleyrshipp** [comment]
Are there any other solutions?  It appears to be depreciated and no longer works. :(

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall terminal-plus and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
