### ISSUE TITLE
win10, atom v1.0.13, terminal-plus v0.4.3 not working

### ISSUE THREAD

**Issue by yzhen123** [jeremyramin/terminal-plus#15]
![360 177806018311879](https://cloud.githubusercontent.com/assets/5233940/9974539/30a4d922-5ec6-11e5-8ecf-af67099e301f.png)

after successfully installed, it just don't show anything and can't type any commands. There are no error message either. But I have to say it could be the best terminal plugin in atom-windows

**Comment by jeremyramin** [comment]
Please try uninstalling and then reinstalling the app. Don't worry, your
settings shouldn't disappear.

**Comment by yzhen123** [comment]
It's still not working.

**Comment by jeremyramin** [comment]
I'll have to take a look and run some tests of my own. I'll notify you here if I need anything, or if I publish a release that fixes this issue.

**Comment by yzhen123** [comment]
I'll really appreciate it.

**Comment by jeremyramin** [comment]
I know what the issue is now. I should have a fix for it soon.

**Comment by yzhen123** [comment]
congratulations！！It's fast.

**Comment by jeremyramin** [comment]
Please update to the latest version of Atom (1.0.15) and try to use the package.

**Comment by yzhen123** [comment]
Thanks, I'll try in few fours.

**Comment by yzhen123** [comment]
I'm sorry to say that it still looks not working...
![qq 20150922154252](https://cloud.githubusercontent.com/assets/5233940/10013084/b99cb46c-6140-11e5-97aa-2e4622aeb945.png)

**Comment by jeremyramin** [comment]
Can you please show me what your console says?

**Comment by yzhen123** [comment]
There are still nothing
![qq 20150922154252](https://cloud.githubusercontent.com/assets/5233940/10013821/6076380c-6147-11e5-8b62-186e76f730c6.png)

**Comment by yzhen123** [comment]
![image](https://cloud.githubusercontent.com/assets/5233940/10013864/c6132580-6147-11e5-882e-67815ad081ff.png)
And I can find the winpty process in my tasklist

**Comment by jeremyramin** [comment]
That means it was launched but it didn't work, which is different from what I originally thought was wrong. I'm surprised that you aren't seeing any error output. This is an issue with a dependency of the package, which I'll have to look at and get back to you.

**Comment by Maistho** [comment]
I seem to have a similar issue, but I also get a message in the console every time I try to open the terminal. 

```
Cannot find module '../build/Release/pty.node' 
C:\Users\maistho\AppData\Local\atom\app-1.0.16\resources\app.asar\src\task.js:47
```

I'm running Windows 10, Atom 1.0.16, Terminal Plus 0.5.1

Please let me know if there's anything I can do to help debug this. =)

**Comment by jeremyramin** [comment]
@Maistho This is because you don't have the tools necessary to compile the native module dependencies of Terminal-Plus (see author's note in README). However, the plugin will still work because I provide precompiled binaries for each operating system.

You can help me reproduce this by giving me the steps you took that lead you to the issue. (i.e. Open and hide, then open and use command `example` leads to this issue.)

**Comment by jeremyramin** [comment]
@Maistho Actually, what language are you using on your computer?

**Comment by RiderSx** [comment]
Same problem. Have properly installed node-gyp and devtools console still reports that pty.node module cannot be found.

**Comment by Maistho** [comment]
@jeremyramin I'm using English UK, but I'm in Sweden and have Swedish time and currency format. Does language affect what binaries are used?

It seems that the winpty process starts (I can see it in taskmgr) but the terminal never loads. (Just a blinking cursor)

**Comment by Maistho** [comment]
I updated to 0.6.0, still have the same issue.
What do I need to install in order to compile the native module dependencies? (I already have nodejs and node-gyp installed globally)

**Comment by jeremyramin** [comment]
@RiderSx There still might be an error causing node-gyp not to compile the binaries properly. The way to check this is to navigate to the pty.js dependency folder for Terminal-Plus and look at the builderror.log file.
Win: `C:\Users\{your username}\.atom\packages\terminal-plus\node_modules\pty.js\builderror.log`
Mac: `/Users/{your username}/.atom/packages/terminal-plus/node_modules/pty.js/builderror.log'

@Maistho I'm starting to think that this might be an issue with the pty.js dependency having a conflict with systems using a different language. I'll have to look through their code and see why this would even be an issue.

**Comment by Maistho** [comment]
What language would it work on? I could test changing my system language or locale and see if that solves it.

Thanks for the link! =)

**Comment by jeremyramin** [comment]
I'm assuming that English is the only language it works on right now. If you could, please try changing the time and currency to English (or English UK in your case). If that still doesn't work, then we need to make sure that there aren't any other settings affecting the language on your system.

**Comment by Maistho** [comment]
Still doesn't seem to work (with english/UK). I'll try installing python and the other things needed for node-gyp and then rebuild, see if that helps.

**Comment by Maistho** [comment]
Also, I'm not sure if this is related, but if I try to uninstall while winpty-agent.exe is running the uninstall fails silently. I have to manually close the process in taskmgr before I can uninstall Terminal-plus

**Comment by yzhen123** [comment]
>but if I try to uninstall while winpty-agent.exe is running the uninstall fails silently. I have to manually close the process in taskmgr before I can uninstall Terminal-plus


I have same problem, winpty-agent.exe process won't be killed after close the terminal tab.

**Comment by jeremyramin** [comment]
This could be a problem with the winpty-agent. I'll find some time in the next couple days to go through the code. Winpty is a dependency of a Terminal-Plus dependency, so I haven't dealt with it much.

**Comment by jeremyramin** [comment]
@Maistho I'm curious. Did installing the proper tools for node-gyp and compiling your own version fix this issue for you?

**Comment by yzhen123** [comment]
@jeremyramin I installed the  vs2012 for desktop, I can find the winpty-agent.exe file in build directory, but there are no pty.node file, so the console shows can't find "../build/pty.node", I tried copy pty.node from bin/ to build/, but It's useless...

**Comment by jeremyramin** [comment]
@yzhen123 Use the following command to rebuild the pty.js dependency from the pty.js folder:
`node-gyp rebuild --target=0.30.6 --dist-url=https://atom.io/download/atom-shell`

**Comment by yzhen123** [comment]
I tried several times but failed because of the poor network or some other reason, I'll keep trying tomorrow.

**Comment by T1mClark** [comment]
This is not a Terminal-Plus issue.  Microsoft has changed the console code in Windows 10 and it breaks current shells on most editors.   The work-a-round is:

1. Bring up a command prompt.  
2. Click on the Settings icon (Top left corner)
3. Select Properties > Options > Check "Use legacy console"
4. Close and re-open ATOM or any other editor and test.

**Comment by yzhen123** [comment]
@T1mClark Thanks!!! it works for me.

**Comment by jeremyramin** [comment]
@T1mClark Thank you! I've been trying to figure this out for days now. I'll have to put this on the README somewhere.

**Comment by T1mClark** [comment]
No Problem.   Thank you for the excellent plugin.

**Comment by SoullessWaffle** [comment]
@jeremyramin you may wanna put this in the author's notes :P

**Comment by jeremyramin** [comment]
@SoullessWaffle You're right, sorry about that. Just added it :)

**Comment by lateau** [comment]
I found kaspersky blocks winpty-agent.exe. I just added a new rule to allows winpty-agent.exe then works perfectly.

**Comment by flyysoul** [comment]
@T1mClark @jeremyramin 
I'm running Win10, Atom 1.2.4, Terminal Plus 0.14.5,I choose "Use legacy console" in a command prompt and close,re-open Atom ,but it`s not work for me (；′⌒`)

**Comment by CalebEverett** [comment]
Running the legacy console in Windows seems to prevent [the new bash feature in build 14316](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows) from running. The terminal pane hangs when you enter `C:\Windows\System32\bash.exe` in the Shell Override. If you start the terminal with cmd.exe and then type in `C:\Windows\System32\bash.exe` it says

```'C:\Windows\System32\bash.exe' is not recognized as an internal or external command,
operable program or batch file.```

Can you point me in the right direction for tracking down how to make this work?

**Comment by rockerest** [comment]
Having the same issue as @CalebEverett: using the legacy console breaks Bash on Ubuntu on Windows. Regardless of that, it didn't fix Terminal Plus either.

I love this Atom plugin, and I appreciate the hard work that went into making it.

That said, "The API changed, so revert to the old API" strikes me as the wrong way to fix this issue.

**Comment by CalebEverett** [comment]
I changed up the font to Lucida Console and it worked with the Shell Override to C:\Windows\System32\bash.exe.

**Comment by senseoki** [comment]
I have a problem. 
win7, atom:1.7.0,
![terminal](https://cloud.githubusercontent.com/assets/8157332/14515446/2b52025c-0235-11e6-8a93-5ee41f998bb6.JPG)

**Comment by KuanYu0729** [comment]
I'm running Windows 10, Atom 1.7.0, Terminal Plus 0.14.5
My terminal-plus is stuck with `Cannot find module '../build/Release/pty.node' `
But I installed 'node-gyp' in global

**Comment by ifVilius** [comment]
still doesnt work with legacy in powershell

**Comment by OwenGH** [comment]
My terminal-plus suddenly not working this morning... Last day it was fine and today when I open the terminal nothing shows up and I cant put any command.

**Comment by arosen93** [comment]
Same for me as well once I updated Atom to 1.7.0.

**Comment by tonimarquez84** [comment]
Me the same. Suddenly Terminal-Plus is not working...

**Comment by EmilioRodrigo** [comment]
Same problem here, it says this message:

"Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."

**Comment by aboe026** [comment]
I'm getting the same issue as @EmilioRodrigo just reported. I recompiled it and am getting the black screen (terminal not actually loading)

**Comment by OClement** [comment]
Same here
Uninstalled, Re-Installed: no dice
Uninstalled, tried to install Terminal-Tokamak (different emulator), same issue

**Comment by johnmarquess** [comment]
All I have on Windows 10 is a blinking cursor with no input.
I uninstalled atom and deleted ~/.atom then re-installed.

I installed node-gyp globally and then installed terminal-plus. I also used legacy in the cmd properites and restarted everything.

This issue only started yesterday.

**Comment by ivankravets** [comment]
Please try PlatformIO Terminal https://github.com/jeremyramin/terminal-plus/issues/223 that is the further development of this plugin.

**Comment by aboe026** [comment]
Thanks @ivankravets, that has the same functionality and works like a charm

**Comment by ystyle** [comment]
@T1mClark but i use "shell override" override to "D:\Programming\Git\bin\bash.exe" , it still no work .

**Comment by WindWen** [comment]
the same problem in windows8.1 , but my cmd.exe dont't have "Use legacy console".

**Comment by EchoBaker** [comment]
**note: ** the plug-in plateformio-ide-terminal is almost like terminal-plus except the name :).

**Comment by WindWen** [comment]
thanks , the plug-in plateformio-ide-terminal can work in my system

**Comment by wsimmerson** [comment]
Same issue, a blinky cursor.  Setting terminal to "legacy" mode doesn't fix the issue.  Same issue if switched to git bash.

**Comment by viciousstar** [comment]
same problem in windows 10, atom 1.8.0-beta1, do not want to use "legacy", any solutions else?

**Comment by cosmology233** [comment]
I had faced same problem and I could solve the problem after trying the steps below. These steps are about installing node-gyp (https://github.com/nodejs/node-gyp/blob/master/README.md).

> * Windows 10:
>     * Install the latest version of npm (3.3.6 at the time of writing)> 
>     * Install Python 2.7 from https://www.python.org/download/releases/2.7/ and make sure its on the System Path> 
>     * Install Visual Studio Community 2015 Edition. (Custom Install, Select Visual C++ during the installation)> 
>     * Set the environment variable GYP_MSVS_VERSION=2015> 
>     * Run the command prompt as Administrator> > 
>     * $ npm install (--msvs_version=2015) <-- Shouldn't be needed if you have set GYP_MSVS_VERSION env> 
>     * If the above steps have not worked or you are unsure please visit http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64 for a full walkthrough> 
> * All Windows Versions> 
>   * For 64-bit builds of node and native modules you will _**also**_ need the [Windows 7 64-bit SDK][win7sdk]> 
>   * You may need to run one of the following commands if your build complains about WindowsSDKDir not being set, and you are sure you have already installed the SDK:

**Comment by nmdanny** [comment]
I'm on windows 10 insider builder 14342 and I also face a similar issue. platformio-ide-terminal seems to work with no issues so I'm using that one as a workaround for now.

**Comment by divmonkey** [comment]
Win 10 x64 also with Atom 1.8.0 and I load up terminal plus, its just empty. I followed that guide above "Use legacy console", still didn't work. Any idea? And oh, I already have Nodejs and Git bash.

**Comment by ivankravets** [comment]
@divmonkey have you tried this https://github.com/jeremyramin/terminal-plus/issues/15#issuecomment-211274878 ?

**Comment by divmonkey** [comment]
@ivankravets Thank you. That works! however it uses the powershell but it'll do :)

**Comment by gikey** [comment]
I found terminal-plus can not work again。atom v1.9.9

**Comment by techsonar** [comment]
I just installed Atom with terminal-plus on top of it and I can't seem to type anything inside. The versions are 1.10.0 and 0.14.5 respectively. I'm on Windows 10 (10586.545 build).

**Comment by shenshouer** [comment]
the same issue for atom 1.10.1 and 0.14.5 on mac osx 10.11.6

**Comment by swapnilchincholkar** [comment]
Same issue atom 1.10.2, 0.14.5 on mac 10.9.5

**Comment by andrezap** [comment]
same issue for atom 1.10.1 on win10

**Comment by shahmir811** [comment]
same issue for atom 1.10.2 on win7

**Comment by turshija** [comment]
I'm having same issue but on MacOS, Atom 1.10.2
When I open terminal, I see only black background with blinking cursor like this: http://www.pics.rs/i/31Nld
My `.atom/packages/terminal-plus/node_modules/pty.js/builderror.log` shows this:


```
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:27:
/Users/{my user}/.atom/.node-gyp/.node-gyp/0.37.8/src/node_object_wrap.h:64:18: warning: 'SetWeak<node::ObjectWrap>' is deprecated [-Wdeprecated-declarations]
    persistent().SetWeak(this, WeakCallback);
                 ^
/Users/{my user}/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:561:12: note: 'SetWeak<node::ObjectWrap>' has been explicitly marked deprecated here
      void SetWeak(P* parameter,
           ^
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:184:
../../nan/nan_maybe_43_inl.h:89:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/Users/{my user}/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:2682:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:184:
../../nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/{my user}/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:3011:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:190:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/{my user}/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:3972:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:592:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:598:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:603:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:609:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1933:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/{my user}/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:2735:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
5 warnings and 4 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/tw/dy1r430n3jd2dqp52w9kpff40000gn/T/apm-install-dir-116813-81670-1asu70i/node_modules/terminal-plus/node_modules/pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by swapnilchincholkar** [comment]
Solution at [321](https://github.com/jeremyramin/terminal-plus/issues/321) worked for me for mac.

**Comment by NatashaKSS** [comment]
Previously tried on Atom 1.9.9

**Comment by phillip-haydon** [comment]
Thanks @NatashaKSS - works perfectly.

**Comment by Zeklandia** [comment]
Atom 1.10.2, Windows 10 Pro, 64-bit, build 1607, 14388.0

Here's the error I get:
```
Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Zeklandia\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Zeklandia\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:10:20)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Zeklandia\.atom\packages\terminal-plus\node_modules\pty.js\index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous>
(file:///C:/Users/Zeklandia/.atom/packages/terminal-plus/lib/process.coffee:1:7)(anonymous function) @ C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:52
4C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)(anonymous function) @ C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:52
```

followed by:
```
C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)(anonymous function) @ C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:52
C:\Users\Zeklandia\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:49 Cannot find module '../build/Release/pty.node'
```

**Comment by wowzaaa** [comment]
same as @Zeklandia :(

**Comment by Zeklandia** [comment]
Same here, @wowzaaa! `platformio-ide-terminal` works fine.

**Comment by konekoya** [comment]
Not sure if it's appropriate to ask here?
`platformio-ide-terminal` works great on my windows 10. But I've run into another problem. I tried to change the default shell to git-bash but after launching the terminal it just opened the git bash not open it inside Atom pane.

**Comment by EnlightonOcean** [comment]
can some one please help me resolve this issue 
![error](https://cloud.githubusercontent.com/assets/12697571/19411269/8077fb74-92cc-11e6-9812-f418ac287e63.JPG)

**Comment by EnlightonOcean** [comment]
Cannot find python executables. Please help

**Comment by EnlightonOcean** [comment]
Getting error while running node-gyp rebuild --target=0.30.6 --dist-url=https://atom.io/download/atom-shell

**Comment by EnlightonOcean** [comment]
Running command C:\Users\mailt.atom\packages\terminal-plus\node_modules\pty.js> node-gyp rebuild --target=0.30.6 --dist-url=https://atom.io/download/atom-shell
is giving following error   

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\mailt\
.atom\packages\terminal-plus\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\mailt\
C:\Users\mailt.atom\packages\terminal-plus\node_modules\pty.js\build\deps\winpty\winpty.vcxproj]

**Comment by guibot17** [comment]
I'm having the same issue with terminal-plus 0.14.5 on Win 10, x64.

events.js:154
Hide Stack Trace
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:523:16)
    at Task.module.exports.Task.send (C:\Users\name\AppData\Local\atom\app-1.11.2\resources\app.asar\src\task.js:117:27)
    at TerminalPlusView.module.exports.TerminalPlusView.input (file:///C:/Users/name/.atom/packages/terminal-plus/lib/view.coffee:261:17)
    at Terminal.<anonymous> (file:///C:/Users/name/.atom/packages/terminal-plus/lib/view.coffee:141:8)
    at Terminal.EventEmitter.emit (C:\Users\name.atom\packages\terminal-plus\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\name.atom\packages\terminal-plus\node_modules\term.js\src\term.js:3493:8)
    at Terminal.keyPress (C:\Users\name.atom\packages\terminal-plus\node_modules\term.js\src\term.js:3243:8)
    at HTMLDocument.<anonymous> (C:\Users\name.atom\packages\terminal-plus\node_modules\term.js\src\term.

I've tried every possible solution given here with no success.
Any help will be appreciated.

**Comment by jeffwudev** [comment]
same issue with terminal-plus 0.14.5 on Win 10, x64 atom 1.11.2

**Comment by Aisuko** [comment]
Did it work? @jeff-wu     The same issue with you

**Comment by Aisuko** [comment]
Did it work? @jeff-wu

**Comment by Dagrut** [comment]
Same issue here, same bug happened (on a fresh install of atom on a debian stable that was just upgraded this morning).
And plateformio-ide-terminal works perfectly.

**Comment by guibot17** [comment]
plateformio-ide-terminal doesn't work for me neither. I have a on Win 10, x64.

**Comment by jarig** [comment]
Doesn't work here as well with the latest stable Atom 1.12.6

**Comment by nrvarun** [comment]
`platformio-ide-terminal `is working but not `terminal plus`. I have a windows 10, x64.

**Comment by dehghani-mehdi** [comment]
Doesn't work here too, I just installed Atom & `terminal-plus`. (windows 10 x64)
(I tired [this](https://github.com/jeremyramin/terminal-plus/issues/15#issuecomment-144618245), but the terminal open seems like it's disable)

**Comment by smolinari** [comment]
I too can't get terminal-plus to work with Windows 10. I am stuck at pty.js not building and failing with 

>Call to 'node -e "require('nan')"' returned exit status -1073741819 while in binding.gyp. while trying to load binding.gyp

I've tried everything mentioned here. 

Edit: I've installed platformio-ide-terminal and it seems to be working. 

Scott

**Comment by smowrey** [comment]
I've too installed platformer-ide-terminal and it worked immediately. Thanks @smolinari

**Comment by jay23794** [comment]
Installing “terminal-plus@0.14.5” failed.Hide output…
Failed to install terminal-plus because Git was not found.
The terminal-plus package has module dependencies that cannot be installed without Git.
You need to install Git and add it to your path environment variable in order to install this package.
You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com
Run apm -v after installing Git to see what version has
**showing this kind of error what to do**

**Comment by abhishekhandacse** [comment]
Processing -File 'E:\CompSci\Project X\Project-X\templates\basic_app\registration.html' failed because the file does not have a '.ps1' extension. Specify a val
id Windows PowerShell script file name, and then try again.
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

**Comment by noahifi** [comment]
I'm going through the Stackskills online couse, "The Python Mega Course," which has a video entitled, "Setting up and Working with the Atom Editor" (4:37). The instructor appears to be using Windows 7. I'm using Windows 10. He shows how to install a useful package, "terminal Plus," and installs it. The "+" appears in the bottom of the Atom status line. I go through the same process and nothing confirms the Terminal Plus packages installs, no error message, nothing to indicate it installed successfully. I does appear in C\Users\Mike\.atom\.apm\terminal-plus with a folder for version 0.14.5. What is the simplest method to get terminal plus working with Atom running under Windows 10?

**Comment by mittalyashu** [comment]
https://github.com/jeremyramin/terminal-plus/issues/15#issuecomment-144618245
Didn't work for me.

**Comment by jazzyjackson** [comment]
Windows 10 x64 v1803
Atom 1.29.0 x64

Use Legacy Console had no effect. Even restarted the pc, no effect.
Installed platformio-ide-terminal works great. Booted into Powershell, ubuntu subsystem bash works 🤷

**Comment by maqboolthoufeeq** [comment]
when i run command

node-gyp rebuild --target=0.30.6 --dist-url=https://atom.io/download/atom-shell

these are the errors

gyp: binding.gyp not found (cwd: C:\Windows\system32) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\MaqboolThoufeeqT\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MaqboolThoufeeqT\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.30.6" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\Windows\system32
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
