### ISSUE TITLE
source bash zsh config files from $HOME

### ISSUE THREAD

**Issue by horvan** [jeremyramin/terminal-plus#162]
On unix systems it would be nice to source config files from $home like .bash_aliases .zshrc .bashrc and so on. This will make the terminal much more convininet as at it's current state.

**Comment by drq883** [comment]
+1

**Comment by RaidoS** [comment]
:+1: +1

so amazing package, and so vexatious should do every time `source ~/.bashrc`

**Comment by grahamb** [comment]
Not sourcing the standard *rc files is a bug. It took me a fair bit of time to figure out why `nvm` wasn't auto-switching to the correct version when I `cd` into a project directory.
