### ISSUE TITLE
Terminal window is cut

### ISSUE THREAD

**Issue by lijunle** [jeremyramin/terminal-plus#17]
See the screenshot:
![2015-09-20-164841_604x349_scrot](https://cloud.githubusercontent.com/assets/1296500/9979934/a37ea03a-5fb7-11e5-823d-f1d67dc3aac6.png)

Repro steps:

1. Open terminal window
2. Resize the atom window to smaller and smaller
3. The terminal is not size responsible, the bottom of terminal window is cut

**Comment by jeremyramin** [comment]
I see what you're saying. I can have the terminal resize smaller with the window but at then at a certain point you reach the minimum terminal height. Does that sound good?

**Comment by lijunle** [comment]
How do you determine the minimun height? You hard code it, or calculate it dynamically on the fly?

**Comment by jeremyramin** [comment]
Calculate it dynamically. I could have the terminal resize down with Atom past the usual minimum of three lines. However I think that the terminal should at least show three lines for displaying command output.

**Comment by lijunle** [comment]
IMO, it could better *not* to do such assumption. We don't know where do Atom running. Just think about user are running on a mobile phone and not having enough room to show three lines. 

By the way, why not make terminal a real Atom panel and let Atom to handle this kind od resizing?

**Comment by jeremyramin** [comment]
The terminal is attached as a real Atom bottom-panel. Atom does not handle the resizing of the bottom panel. If you try resizing Atom smaller without the terminal, you'll see that the Atom status-bar begins to disappear at some point. This is why the best I can do is track the window resizing and have the terminal resize smaller with Atom.

**Comment by jeremyramin** [comment]
The latest release (v0.6.0) should have the resizing to Atom window. Hopefully it is designed as you requested.

**Comment by lijunle** [comment]
Thanks @jeremyramin , the fix is awesome! :+1:
