### ISSUE TITLE
terminal does not honor color codes

### ISSUE THREAD

**Issue by crmckenzie** [jeremyramin/terminal-plus#18]
Platform: Windows

When I run rspec the colorized output is not honored. Instead, the color codes are printed directly.
Despite this issue, this is a really great plugin. Thank you :)

### Example
```
Finished in 0.95106 seconds (files took 4.29 seconds to load)
←[32m272 examples, 0 failures←[0m
```

**Comment by jeremyramin** [comment]
Thank you for your complement and I appreciate you taking the time to report this issue. I'll add this to the list of things to fix and let you know once a fix has been published. I apologize in advance if it takes several days to get to this, I don't have as much free time right now.

**Comment by jeremyramin** [comment]
I just had a chance to test this on my Windows machine with rspec, and I can't seem to be able to reproduce this issue.
![image](https://cloud.githubusercontent.com/assets/3977054/10003565/d0affa18-6061-11e5-992b-985287cb0ba3.png)

Some questions you can answer to help me figure out what is wrong:
1. Which version of Windows are you using?
2. Which shell are you using? (Default is Powershell)
3. Are there other commands that should be colored and produce this issue? (i.e. npm, grunt, etc.)

**Comment by crmckenzie** [comment]
OS: Windows 7 x64
Shell: Powershell

Further review shows that it appears to be an issue when rspec is running under autotest.
### Output under rspec
![image](https://cloud.githubusercontent.com/assets/947569/10004174/3773ddc0-6065-11e5-8acf-65212057340d.png)

My configuration is:

### /.rspec
```ruby
--color
```

### /.autotest
```ruby
require "autotest/bundler"
require "autotest/restart"

Autotest.add_hook :initialize do |autotest|
  ['spec/integration'].each do |file|
    autotest.add_exception file
  end
end

Autotest.add_hook :initialize do |autotest|
  autotest.add_exception(/log/)
end

Autotest.add_hook :initialize do |autotest|
  %w{.git ._* vendor tmp log doc}.each do |exception|
    puts "adding autotest exception #{exception}"
    autotest.add_exception(exception)
  end
end

=begin
CLEAR = "\e[2J\e[f"
LINE  = "\n"*2 + '-'*80 + "\n"*2

##
#  # From autotest/growl
#    # Set the label and clear the terminal.
Autotest.add_hook :run_command do
  print LINE
  print CLEAR
  false
end
=end
```

### Output under autotest
![image](https://cloud.githubusercontent.com/assets/947569/10004119/e73ed95e-6064-11e5-929f-ae52266119eb.png)


The output is much more distracting when trying to scan through the actual test output:
![image](https://cloud.githubusercontent.com/assets/947569/10004241/88bd5d78-6065-11e5-9512-2d444d81548f.png)

**Comment by jeremyramin** [comment]
If you could, please test the `autotest` command in the external Powershell. Do you see the proper output?

**Comment by crmckenzie** [comment]
You are onto something. I've been using ConEmu as my default terminal for a long time and this problem does not present there. However, in the external powershell console the problem does present. Conclusion, the problem is not in your code--it's in the shell's inability to display 256 colors.

Thanks for helping me track this down.

**Comment by jeremyramin** [comment]
No problem, I'll go ahead and close this issue then.

**Note:** You can specify a different shell in the Terminal-Plus settings with the `Shell Override` setting. Changing the shell to match the one used by ConEmu might be the solution to your problem.
