### ISSUE TITLE
Simplified Chinese display error

### ISSUE THREAD

**Issue by asmpg** [jeremyramin/terminal-plus#183]
Simplified Chinese character take up two characters space,in terminal-plus only one .Thank You.

**Comment by asmpg** [comment]
It seems that no one maintain this project anymore . Close issue.

**Comment by UziTech** [comment]
This package is no longer maintained. Please install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
