### ISSUE TITLE
Needs workaround for Atom's NODE_ENV variable leaking into terminal, npm install fails

### ISSUE THREAD

**Issue by raniesantos** [jeremyramin/terminal-plus#187]
When I type `npm install` it does **literally** nothing, no errors are logged.
After a long search I've read that the `NODE_ENV` variable within Atom itself is leaking into terminal plugins, this is always set to production therefore directly affecting the `npm install` command and preventing me from installing devDependencies.

[Link to other Atom package that seems to have solved this](https://github.com/ziyasal/atom-open-conemu-here/pull/3)

**Comment by AlicanC** [comment]
Oh, I was wondering why my application kept starting in production mode. +1
