### ISSUE TITLE
terminal automatically closing

### ISSUE THREAD

**Issue by daenney** [jeremyramin/terminal-plus#2]
When I try to open up the terminal the pane slides open, something is printed and then slides shut again. I can't see what exactly but I expect some kind of error.

**Comment by jeremyramin** [comment]
@daenney I think I know what could be wrong. If you don't mind me asking,
1. What system are you on? (OS X, Windows, Linux)
2. What is your standard terminal? (bash, cmd.exe, powershell, sh, zsh)

**Comment by miguelcarax** [comment]
I have the same issue, ArchLinux and I'm using zsh.

**Comment by jeremyramin** [comment]
Is that your default shell? Or did you override it in the settings?

**Comment by miguelcarax** [comment]
Bash it's default, but i'm using zsh out of atom

**Comment by jeremyramin** [comment]
Interesting. It is picking up on the correct shell yet it is having trouble launching it. In the next 20 minutes I'll release an update. Let's see if it fixes the issue.

**Comment by miguelcarax** [comment]
Nice! I'll be notice if it's fixed :) thx

**Comment by jeremyramin** [comment]
@miguelcarax The next update won't fix the issue, but it will leave the terminal open after the issue. If you could copy and paste the output here so I can see it, that would be very helpful.

**Comment by daenney** [comment]
In my case it's OS X 10.11 with Fish 2.2 as my default shell.

**Comment by jeremyramin** [comment]
@daenney If you could tell me what happens now with the latest update, that would be very helpful.

**Comment by daenney** [comment]
This is what I get:

**Comment by jeremyramin** [comment]
@daenney Thanks. I posted an update. Let me know if this fixes your issue.

**Comment by daenney** [comment]
Yap, aces! :100:

**Comment by Grawl** [comment]
Just got exactly this problem running a terminal pane with “Shell Override” option set to just `fish`:
`execvp(3) failed.: No such file or directory`

It was strange because I not got this error yesterday. Set it to `/usr/local/bin/fish` as in my OS X Terminal.app options and it works great.

Maybe you will add more human-understandable error on this exception? Like “Shell Override is set to missing binary, please change this option (try to copy this from your other terminal settings that you already set up).” or something similar.

**Comment by jeremyramin** [comment]
Just putting `fish` should work unless `/usr/local/bin` is not located in your PATH environment variable. The error you see is provided by a dependency of Terminal-Plus but you are right. The errors should be more understandable. I will look into getting that fixed.

**Comment by Grawl** [comment]
If I wrote just `fish` into Terminal.app, it launches. So `/usr/local/bin` is located into `PATH`.
