### ISSUE TITLE
Terminal No Longer Functional

### ISSUE THREAD

**Issue by Nemesis9765** [jeremyramin/terminal-plus#209]
Just updated the terminal-plus plugin a couple days ago and haven't been able to use terminal since.  Whenever the terminal appears, all that appears in the terminal is the blinking cursor and no prompt.  This is using Atom 1.7 w/ terminal-plus 0.14.5.  I've attempted to uninstall the plugin and re-install w/ no effect.

![image](https://cloud.githubusercontent.com/assets/1054015/14358128/44282e34-fcb1-11e5-9ba5-f68d9001782c.png)

**Comment by voliva** [comment]
Duplicate of #201?

**Comment by Nemesis9765** [comment]
Actually yeah, it's the same, I'll close this one out.

Thanks
