### ISSUE TITLE
Hidden prompt

### ISSUE THREAD

**Issue by yoorek** [jeremyramin/terminal-plus#21]
on Mac prompt is hidden under "status bar" (not initially, but run any grunt/gulp task and stop it using CTRL-C). You do e.g "ls" see content of folder but prompt is not visible
<img width="796" alt="zrzut ekranu 2015-09-25 o 09 34 10" src="https://cloud.githubusercontent.com/assets/271500/10095278/db03e7b8-6368-11e5-9763-c5cf7318ac8a.png">

**Comment by jeremyramin** [comment]
Thanks for reporting this. I'll see if I can reproduce this and then get back to you.

**Comment by jeremyramin** [comment]
This should be fixed in the latest update (v0.6.1). Please test the latest update and close this issue if your issue has been resolved.

**Comment by yoorek** [comment]
It's fixed! Thanks!
