### ISSUE TITLE
Terminal is not working

### ISSUE THREAD

**Issue by mairanteodoro** [jeremyramin/terminal-plus#221]
I can start up Atom and click on the plus symbol to open a terminal. However, it seems that the terminal just hangs and does not show anything (see the attached screenshot).

![screenshot 2016-04-14 14 01 29](https://cloud.githubusercontent.com/assets/7604069/14538367/7224e9b0-0249-11e6-8925-5c3460aa504b.png)

**Comment by ivankravets** [comment]
Please take a look at PlatformIO fork https://github.com/platformio/platformio-atom-ide-terminal

**Comment by mairanteodoro** [comment]
Great! Thanks!

**Comment by JestonBlu** [comment]
I have the same issue.. is this project no longer active?

**Comment by mairanteodoro** [comment]
Hi, JestonBlu! If you're having the same issue as me, you can go to Atom -> Preferences -> Install  and search for a package called "platformio-ide-terminal". This package is essentially the same as "terminal-plus".

**Comment by adi518** [comment]
@JestonBlu The guy above forked this project and fixed whatever bugged it from working, so use that, you can the original one installed and if it gets updated, ditch/disable the forked version and go back to it. Thanks Ivan!

**Comment by benlavender** [comment]
I had the same problem after updating to the latest release of Atom last week, simply install the forked version.

apm install platformio-ide-terminal

**Comment by HerneWyldwood** [comment]
Same problem on windows 10 since update to most recent version of atom.

**Comment by mairanteodoro** [comment]
If you're having this issue, just follow what @ivankravets suggested.
