### ISSUE TITLE
Automatic directory switching

### ISSUE THREAD

**Issue by Tiseno** [jeremyramin/terminal-plus#24]
I would love an option for the terminal to automatically switch directory when switching to another file. Alternatively an option which makes the toggle command check if there is a terminal in the directory of the current file and if not open a new instace for that directory.

**Comment by jeremyramin** [comment]
Let me make sure I am understanding your request correctly,
1. When switching to another file view, have your active terminal change directories into the new directory.
or
2. On toggle, open the first terminal with the same directory as the current file. Open a new terminal if necessary.

Side effects of each:
1. Your command history would fill with `cd` commands. A workaround could be made for this.
2. If you have a terminal open when you switch to a new file, you would have to toggle close and then toggle open to find the right terminal. Minor inconvenience in my opinion but if you don't mind then it can be done.

**Comment by Tiseno** [comment]
Both 1 and 2 would be almost equally good in my case and i see the problems with option one. Another option that would work would be to force close the active terminal and then start a new one in the new selected files directory. A con with option 2 would be that it would create a lot of terminals when working in multiple folders, a pro would be that history is kept.

All in all i think option 2 makes the most sense to be added as an option.

**Comment by jeremyramin** [comment]
A similar issue with the option 2 is that if there are multiple terminals with the same directory, it would just open the first one which might happen to be a busy terminal.

**Comment by Tiseno** [comment]
Right now the toggle doesn't care if the terminal is busy so it is consistent. If you are not planning on adding a 'Open new terminal if current terminal is busy' option for the toggle that is.

**Comment by jeremyramin** [comment]
I guess you are right. I'll add option 2 to the list of enhancements and get back to you once it has been released.

**Comment by jeremyramin** [comment]
v0.10.0 release has something similar to what we discussed. In the options, you can set terminals to map to files or folders. Additionally, you can set if you want a new terminal to be created if one does not already exist. I believe this gives you more control over how often you want the terminal to switch. Please give it a try and let me know what you think.

Options to look at: `Map Terminal To` and the toggle below it `Auto Open New Terminal`

**Comment by Tiseno** [comment]
When switching to another file while the terminal is open the feature works as intended. But when opening a new terminal for a new file it does not create a new one.

**Comment by jeremyramin** [comment]
I have it set up so it will only switch or create a new terminal if a terminal view is currently open. For the new terminal feature to work as intended, make sure you have the terminal mapping set to `File` and the toggle below the terminal mapping called `Auto Open New Terminal` enabled.
