### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by emacspinky** [jeremyramin/terminal-plus#241]
I was using terminal-plus last week, and it was working great. This week, it no longer shows the current working directory at startup, and I cannot seem to type anything in the terminal. I'm on Mac OSX El Capitan 10.11.4, using Atom 1.7.2.

![screen shot 2016-04-25 at 9 15 59 am](https://cloud.githubusercontent.com/assets/8058791/14786840/5e26b918-0ac6-11e6-87ca-d2074f43d1be.png)

**Comment by mairanteodoro** [comment]
I had the same problem a while ago. You have to install a forked (and fixed) version that resides here: https://github.com/platformio/platformio-atom-ide-terminal

**Comment by emacspinky** [comment]
Well, that appears to have worked. Thanks, a lot!

**Comment by mairanteodoro** [comment]
Sure!
I seems that Terminal-Plus is no longer supported by recent versions of Atom and the package creator is no longer maintaining it.
