### ISSUE TITLE
No prompt and no entry

### ISSUE THREAD

**Issue by jekoehler** [jeremyramin/terminal-plus#245]
Hi Jeremy!

I am new to Atom and installed your terminal-plus package. There are no issues but I cant enter any text to the terminal window. I just see a white cursor without any prompt.

terminal-plus v0.14.5
Atom v1.7.3
no package issues

**Comment by KayJay89** [comment]
I'm in the same boat as you.

**Comment by QueueHammer** [comment]
Same issue.

**Comment by Karstenan** [comment]
I have the same problem.

**Comment by marinhog** [comment]
same problem here...but...I uninstalled and now I cannot reinstall it!

**Comment by bruinebeer** [comment]
Had the same issue, couldn't even uninstall it..
I did a reinstall via the terminal. Open your terminal / command prompt and enter:

```shell
apm install terminal-plus
```

It doesn't matter if you already have it installed.
Hope this helps guys!

**Comment by rofrol** [comment]
https://github.com/jeremyramin/terminal-plus/issues/255

**Comment by kulinp** [comment]
Same issue, no prompt, no errors, white blinking cursor. I tried changing the prompt from the default (blank but chooses powershell) to cmd.com but no joy. Using Windows 10.

terminal-plus v0.14.5
Atom v1.7.3
no package issues

**Comment by panCtrlV** [comment]
having the same issue

**Comment by colinharris05** [comment]
Same as described by @kulinp. Would love to have this package. Using MacBook Pro 2011, macOS Sierra

**Comment by rofrol** [comment]
use https://atom.io/packages/platformio-ide-terminal

It works

**Comment by mbach04** [comment]
Same problem here with a fresh atom install 1.11.2.

**Comment by tomptaylor** [comment]
same here

**Comment by oguzbilgic** [comment]
I have the same issue:

Atom v1.11.2
terminal-plus v0.14.5

**Comment by TerrenceBeckham** [comment]
@mbach04 Thanks that worked for me

**Comment by zachre** [comment]
hey everyone - i'm also having this problem (started as soon as I updated my terminal-plus plugin. blinking cursor, no prompt, cannot enter text into the terminal window. opens and closes as expected, however.

Atom v1.12.3
terminal-plus v0.14.5
it's been six months since this was originally posted - can we get an update on this from the author?? @jeremyramin   (i really loved this plugin when it was working)

**Comment by vpdwebdesign** [comment]
@rofrol thanks for your suggestion. Switched to platformio-ide-terminal. I'm back to my normal self now :) For those who have [_metathesiophobia_](http://www.fearof.net/fear-of-change-phobia-metathesiophobia) or something similar, do not worry. platformio-ide-terminal is a fork of terminal-plus, so it inherits the same awesome genes. It even has a solarized dark theme if you love that. Maybe you could all switch to that in the meantime before @jeremyramin fixes this issue.

**Comment by ijm51000** [comment]
@rofrol Thanks platform-ide-terminal does what I need, new to atom, so not missing anything, only went with terminal-plus because it had the most downloads.

**Comment by droarty** [comment]
I had terminal-plus working all year but then one day Atom crashed and I wasn't able to get terminal plus working again.  But platformio-ide-terminal worked for me as well.  Thanks.

**Comment by apetta** [comment]
Having this issue as well (Windows 10)

**Comment by jpelton-stroud** [comment]
anybody find a solution _other than_ simply switching to the platformio fork?  fresh atom 1.30 install w/o any other packages, i get the same "blinking cursor, no prompt".  Working on a Pixelbook in beta channel w/ penguinvm/crostini...

<pre>jpstroud@penguin:~$ apm install terminal-plus
Installing terminal-plus to /home/jpstroud/.atom/packages ✓
jpstroud@penguin:~$ node -v                                       
v8.12.0
jpstroud@penguin:~$ npm -v
6.4.1</pre>

**Comment by droarty** [comment]
Sorry this isn't helpful if you are forced to use atom for some reason.  But I moved on to the free version of vscode a couple months ago and forgot all about this issue.  Terminal windows are built in to the product.

**Comment by brucehvn** [comment]
I switched to the platform-io fork as well.  It seems to work fine.  I've been without the terminal for so long, it's nice to have it back.

**Comment by rachana754** [comment]
Same issue. Cannot figure out why it is not working. I can see just a blinking white cursor.
Please help.

**Comment by webmasterpf** [comment]
atom 1.35.1 and same issue, no prompt and blinking white cursor

**Comment by codersofthedark** [comment]
atom 1.42.0 (macOS Catalina Version 10.15.1 )and same issue, no prompt and blinking white cursor.

Also, `apm install terminal-plus` didn't work either.

**Update**: This repo is no longer maintained hence won't work. It has been replaced by [platformio-ide-terminal](https://atom.io/packages/platformio-ide-terminal)
