### ISSUE TITLE
Not working with Atom V1.7.3

### ISSUE THREAD

**Issue by amandeepmittal** [jeremyramin/terminal-plus#246]
It says, terminal-plus is not compatible with the newest version of Atom and the package fails to load. Are you going to update it? 

Following:

```
terminal-plus 0.14.5

pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.

Incompatible package.
```

**Comment by sjayanna** [comment]
@amandeepmittal works fine for me on 1.7.3 
I'm on Mac OSX 10.11.4

**Comment by amandeepmittal** [comment]
I am also using El Capitan OS X 10.11.4 but I recently updated Atom and now it fails to load.

**Comment by sjayanna** [comment]
Yeah works like a charm! Try uninstalling and re-installing it back?

**Comment by pdsullivan** [comment]
Same happing to me after i updated to 1.7.3. Will try uninstalling and re-installing.

**Comment by amandeepmittal** [comment]
@pdsullivan I did, still the same error.

**Comment by cabao** [comment]
I met the same problem, too
On ubuntu Linux 14.04LTS

**Comment by nyrrad** [comment]
Atom 1.7.3
Linux Mint 17.2

After uninstalling and reinstalling did not fix the problem

**Comment by robertosf92** [comment]
Found a way to fix it. In my case a red bug appeared on the right down corner. Clicking on it showed that a package was outdated, just click recompile and reopen the app. In my case it worked

**Comment by amandeepmittal** [comment]
@robertosf92 thanks a lot. It solved!

**Comment by cabao** [comment]
@robertosf92 Excuse me ,what OS do you use?
I click the red bug and rebuild the terminal-plus
But it still doesn't work

**Comment by amandeepmittal** [comment]
After rebuilding it, you have to reload the Atom. Either the "Reload Atom" button will appear itself after building packages or you have to close it and then start it. I am using OS X 10.11

**Comment by robertosf92** [comment]
@cabao Ubuntu 16.04 sorry it took this long. It's as amandeepmittal said, reload Atom
