### ISSUE TITLE
Possible to move tab to the right?

### ISSUE THREAD

**Issue by sjayanna** [jeremyramin/terminal-plus#247]
Is it possible to change a setting to move the terminal window to the right instead of bottom (as shown)

<img width="1275" alt="screen shot 2016-04-29 at 12 50 43 pm" src="https://cloud.githubusercontent.com/assets/194508/14923078/035b6eca-0e09-11e6-9101-c854ee5cfc87.png">

**Comment by MrCelticFox** [comment]
Yes: you can move a terminal to its own tab by dragging the terminal icon to the tabs bar, see issue #9

**Comment by sjayanna** [comment]
Thank you @MrCelticFox @jeremyramin  This https://github.com/jeremyramin/terminal-plus/issues/9 seems to do the job
