### ISSUE TITLE
Terminal-plus won't work on atom 1.0.19

### ISSUE THREAD

**Issue by cheunghy** [jeremyramin/terminal-plus#25]
<img width="1440" alt="screen shot 2015-10-06 at 1 01 56 pm" src="https://cloud.githubusercontent.com/assets/3055936/10300546/7eadd3dc-6c2a-11e5-898d-3f48d26be2a9.png">

**Comment by jeremyramin** [comment]
@cheunghy If you click `Rebuild Packages` it should work after that.

**Comment by cheunghy** [comment]
It works, Thanks.

By the way, what's the causing?

**Comment by jeremyramin** [comment]
@cheunghy Atom thinks the package will stop working on the latest update. It disables the package until you tell Atom to rebuild it for the latest version.

**Comment by cheunghy** [comment]
Is there any way to make it work without clicking `Rebuild Packages`?

**Comment by jeremyramin** [comment]
It works without clicking it, Atom just wont enable it unless you click `Rebuild Packages`. You can uninstall the package and reinstall it to avoid this but that takes more time.

**Comment by jeremyramin** [comment]
Closing this issue as it has been solved.

**Comment by cheunghy** [comment]
Thanks
