### ISSUE TITLE
press CTRL+C to quit

### ISSUE THREAD

**Issue by mobileloft** [jeremyramin/terminal-plus#27]
press CTRL+C to quit
not work.
1.OS X EI Capitan
2.bash
3.
![image](https://cloud.githubusercontent.com/assets/11615631/10328566/eaffb014-6ce8-11e5-914f-3ba61dd3f505.png)

**Comment by jeremyramin** [comment]
If you could provide me with some more details, we can figure out why CTRL+C doesn't work for you.
1. What is your operating system?
2. What shell are you using? (bash, zsh, powershell, cmd)
3. What command are you running when you try to CTRL+C?

**Comment by jeremyramin** [comment]
I didn't see that you edited your original issue, thank you for the information. Later I'll try and reproduce this and let you know if I need anything else.

**Comment by JostCrow** [comment]
I have the same problem and so is a collegue of mine.

1. Ubuntu 15.04 (collegue uses OSX)
2. Bash
3. python manage.py runserver

**Comment by jeremyramin** [comment]
Ah so it's a problem with sending the SIGINT to python. I'll try and find a simple python script to run and figure out what is wrong.

**Comment by jeremyramin** [comment]
Upon further review, I have determined this to be an issue that only affects bash prompts. I'm currently exploring why only bash is affected. Any input from third parties is welcome. I noticed that I can get bash to respond to `Control+C` correctly if I switch to another shell (zsh for example) and then call `exec -l bash`.

**Comment by jeremyramin** [comment]
I believe this has been fixed v0.9.0. Please give it a try and let me know if it works for you.

**Comment by JostCrow** [comment]
For me it is working now.

**Comment by jeremyramin** [comment]
@JostCrow That's good to hear. Sorry it took so long to get a fix.

**Comment by jeremyramin** [comment]
Closing this issue as it has been resolved as of v0.9.0
