### ISSUE TITLE
Just a quick thanks!

### ISSUE THREAD

**Issue by msguerra74** [jeremyramin/terminal-plus#29]
This isn't an issue, I just wanted to let you know that I've been searching a long time for the right terminal integration for Atom and this one seems to be the one I've been waiting for! I've tried several before and there was always something that kept me from continuing to use them, so I thought I'd pop in here to quickly say thanks for finally making one that actual works like the regular Terminal app!

**Comment by jeremyramin** [comment]
I appreciate the compliment, it means a lot. Thank you for using my package. I'm glad you like it.
