### ISSUE TITLE
Terminal Plus will not let me type text or connect to my terminal

### ISSUE THREAD

**Issue by swheatley** [jeremyramin/terminal-plus#299]
1)  Uninstall and reinstall completed

2) Tried:   apm install terminal-plus( nothing )

3)  All I see is the yellow terminal and blinking cursor

**Comment by radix** [comment]
I just installed terminal-plus on a fresh install of atom and I'm getting exactly this behavior. just getting a blank terminal with blinking cursor and no shell prompt or error.

**Comment by Coysh** [comment]
Same here on Windows 7. Tried uninstalling and reinstalling from both Atom and command line. Is this a permissions thing (E.g. running as admin?)
![image](https://cloud.githubusercontent.com/assets/5764356/16725347/bb16b334-474e-11e6-90d0-02f5f34289b2.png)

**Comment by claudiodangelis** [comment]
It works for me with atom 1.6.2, but it does not work (same behavior reported by others) with 1.9.0-beta0.

**Comment by ramonsantos** [comment]
Try https://github.com/platformio/platformio-atom-ide-terminal

**Comment by DanielApt** [comment]
I also have this issue, and using the above link does not help.

With terminal-plus I get a blank screen, with platformio-atom-ide-terminal I get the following error:

```
execvp(3) failed.: No such file or directory
```

[See issue here](https://github.com/platformio/platformio-atom-ide-terminal/issues/5)

Anyone know how to address this issue?

**Comment by kelceywilson** [comment]
Same problem here.

**Comment by xykj61** [comment]
Same here.

**Comment by scriptonian** [comment]
same here

**Comment by claudiodangelis** [comment]
Here's a temporary workaround: https://github.com/jeremyramin/terminal-plus/issues/402

**Comment by bhison** [comment]
@claudiodangelis thank you so much!

**Comment by workerbee22** [comment]
Uninstalled package

**Comment by rnoxy** [comment]
Same issue 👎 
Uninstalled package

**Comment by J-Rojas** [comment]
This package is a fork of terminal-plus and doesn't exhibit this bug ( tested on Mac running High Sierra)

https://atom.io/packages/tokamak-terminal

**Comment by sanketdhande** [comment]
your terminal might be outdated , update it and restart atom

**Comment by newwhitecheng** [comment]
In Mac

1. Open Atom and use shortcut to open setting by
`Cmd  ,`
2. At Search Package, type
`terminal-plus`
3. Click disable
4. At Search Package, type
`platformio-ide-terminal`
5. Install platformio-ide-terminal and click Enable
6. Restart Atom

**Comment by Rachit1612** [comment]
Try uninstall platformio-ide-terminal and install it again ....and also check shell override field for any leading or trailing spaces.
