### ISSUE TITLE
Terminal Not displaying anything and is unusable when opened...

### ISSUE THREAD

**Issue by green1139** [jeremyramin/terminal-plus#306]
I have tried restarting Atom, but doesn't help me...
Please help me!

atom --version 
Atom    : 1.10.0-dev-e92e2c0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by aakhmetz** [comment]
as it was proposed in another issue, i tried https://github.com/platformio/platformio-atom-ide-terminal and it worked for me

**Comment by jadenPete** [comment]
I have the same issue

**Comment by sourcec0de** [comment]
@jadenPete 

@aakhmetz fix works. Just install `platformio-ide-terminal` for now.

**Comment by jadenPete** [comment]
Yeah it works 4 me 2

**Comment by green1139** [comment]
Thanks everyone! I am using platform-ode-terminal for **now**...
