### ISSUE TITLE
Pty.js (actually is winpty) build fail on windows machine

### ISSUE THREAD

**Issue by zmLGBBM** [jeremyramin/terminal-plus#32]
I'm using Windows 10 64bit with Visual Studio 2015 Ent.

**Terminal-plus** doesn't work because it failed to build `pty.js`. When trying to build `pty.js` manually using `node-gyp rebuild`, it keeps fail on `winpty`. That `winpty` is **really really** old.

Can this be fixed?

**Comment by jeremyramin** [comment]
Even if pty.js fails to build, I provide prebuilt binaries that are automatically used. On another note, `winpty` is very old. I am running off of my own fork and I've considered updating to the latest version and fixing any errors that would result. It's on the list of things to do.

**Comment by zmLGBBM** [comment]
@jeremyramin Really great to hear that.

Yes, I've noticed you provided prebuilt binaries, but it's for previous version of **atom**, and since I'm using 1.0.19, it requires me to rebuild one for the newer version. Well, then it fails.

Anyway, thanks for the package!

**Comment by jeremyramin** [comment]
Sorry to hear that. Do you happen to have a copy of the error it displays when the rebuild fails?

**Comment by jeremyramin** [comment]
I updated winpty to the latest version from . You should be able to compile with it now. Tested it on Windows 8 with Visual Studio 2013.

**Comment by zmLGBBM** [comment]
@jeremyramin Great! It works. I can now see the `winpty.dll` and `pty.node` in the `Realese` folder. Thanks.

Which commit does this related to?

**Comment by jeremyramin** [comment]
@zmLGBBM If you want to see updates to the pty.js dependency, you'll have to look at my fork of the repository.

[jeremyramin/pty.js](https://github.com/jeremyramin/pty.js)

**Comment by zmLGBBM** [comment]
@jeremyramin Yep, is that the one you authored on Sep 10?

https://github.com/jeremyramin/pty.js/commit/832c3a34c2e3ba5cc3c7add87320560dea77ecff

**Comment by jeremyramin** [comment]
My apologies, I should have been more clear. It is jeremyramin/pty.js@f7d2eeeb03d8de2f94df0fe3557abf6025f45cba. I switched from the previously used rpeters/winpty fork to the main repository rprichards/winpty.

**Comment by zmLGBBM** [comment]
@jeremyramin Thanks for the hint. It should occur to me to check other branches.

**Comment by jeremyramin** [comment]
Issue fixed as of v0.9.0
