### ISSUE TITLE
can't input anything

### ISSUE THREAD

**Issue by dccrazyboy** [jeremyramin/terminal-plus#340]
hi, i install terminal-plus 0.14.5 on atom 1.10.2  osx 10.10.3 
but when i click the plus button and create a plan, there is only black and i can't input anything

just like this 

![image](https://cloud.githubusercontent.com/assets/2993912/18613706/8b9fa850-7db2-11e6-879f-c25aec581004.png)

what can i do?

**Comment by dccrazyboy** [comment]
The cursor is constantly flashing

**Comment by partizanos** [comment]
same problem here I also installed the node-gyp
nod install -g node-gyp and nothing happened

**Comment by partizanos** [comment]
I am trying that  aparraently it's common issue https://github.com/jeremyramin/terminal-plus/issues/338

**Comment by JuanVqz** [comment]
me too @dccrazyboy, can you help me?

**Comment by dccrazyboy** [comment]
I tried `platformio-ide-terminal` .
Problem solved!

**Comment by JuanVqz** [comment]
Gracias mi buen amigo!! Thanks, my friend! Cool! Close the issue, please
