### ISSUE TITLE
Applying themes?

### ISSUE THREAD

**Issue by pierrenel** [jeremyramin/terminal-plus#35]
How does one apply the themes that are in the repo? I can't seem to find the instructions anywhere - I've even tried dropping some less/css into my Atom Stylesheet - but that didn't change anything. 

Thanks!

**Comment by jeremyramin** [comment]
@pierrenel You can apply themes in one of two ways:
1. Navigate to the Terminal-Plus settings (`Preferences > Packages > Search 'Terminal-Plus'`) and choose one of the built-in themes under the `Theme` dropdown.
2. Use the [template provided in the README](https://github.com/jeremyramin/terminal-plus#themes) to create your own theme.

**Comment by pierrenel** [comment]
Yay thanks so much for the info, all better now.

**Comment by jeremyramin** [comment]
No problem. Hope you like Terminal-Plus.
