### ISSUE TITLE
how can I change the default terminal?

### ISSUE THREAD

**Issue by danpantry** [jeremyramin/terminal-plus#37]
I'm on a Windows machine, so `terminal-plus` defaults to using Windows Powershell. I have Git Bash installed on this machine and I'd like to use that as my terminal instead. How can I achieve this? There's no mention of this scenario in the docs.

Thanks!

**Comment by danpantry** [comment]
Never mind - this is pretty simple. Open the Packages/Settings window, click Setting then `terminal-plus`. Then change the Shell Override setting.

**Comment by jeremyramin** [comment]
Understandable considering the lack of documentation for the setup of Atom. Welcome to the community and I hope you like my terminal package.
