### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by lvansnippenburg** [jeremyramin/terminal-plus#388]
terminal-plus 0.14.5

pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 49, got 46.

**Comment by lvansnippenburg** [comment]
Just do a rebuilt within Atom and it is gone!

**Comment by willin** [comment]
no use
