### ISSUE TITLE
Can't clear sceen

### ISSUE THREAD

**Issue by AbdullahAli** [jeremyramin/terminal-plus#39]
Not really an issue, more of a feature request.

It would be great to add a shortcut to clear the screen, ie: cmd-k to clear the screen

For example, if I am in a rails console, I can't use `clear`, so the shortcut would be great in such a scenario

Thank you

**Comment by jeremyramin** [comment]
v0.10.0 has this now. Please give it a try and let me know if it works for you.

**Comment by AbdullahAli** [comment]
thank you for sorting that out so quickly - works really nicely! :tada: @jeremyramin
