### ISSUE TITLE
Terminal not working in mac OS Sierra.

### ISSUE THREAD

**Issue by sarment0** [jeremyramin/terminal-plus#398]
I just installed and it opens a black terminal and i can't type anything. 

<img width="1132" alt="screenshot 2016-11-22 10 49 52" src="https://cloud.githubusercontent.com/assets/770065/20524468/cbb1177c-b0a1-11e6-9f9d-e336c0a239af.png">

**Comment by esparkman** [comment]
+1

**Comment by ubergeekzone** [comment]
+1, use [Platformio Ide Termina](https://atom.io/packages/platformio-ide-terminal)l to fix. this is a fork of terminal-plus.

**Comment by inferal** [comment]
+1

**Comment by sarment0** [comment]
@ubergeekzone I installed and the issue remains.
Do i need to config something to work properly at Mac OS Sierra?

**Comment by sarment0** [comment]
@ubergeekzone  I uninstalled the other plugin and now is running smooth. 
Tks.
