### ISSUE TITLE
Fail to install into ATOM 

### ISSUE THREAD

**Issue by binhor009** [jeremyramin/terminal-plus#4]
i'm attemping to install you packge but i got some error.... look the output below: 

Installing “terminal-plus@0.1.6” failed.Hide output…

> pty.js@0.3.0 install /tmp/apm-install-dir-115810-7379-150zpvb/node_modules/terminal-plus/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-115810-7379-150zpvb/node_modules/terminal-plus/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory `/tmp/apm-install-dir-115810-7379-150zpvb/node_modules/terminal-plus/node_modules/pty.js/build'

make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-62-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115810-7379-150zpvb/node_modules/terminal-plus/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-62-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/myuser/.atom/.apm/.apmrc" "--userconfig" "/home/myuser/.atom/.apmrc" "install" "/tmp/d-115810-7379-1idt3og/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115810-7379-150zpvb/npm-debug.log

**Comment by jeremyramin** [comment]
@binhor009 You need `g++` to compile the dependencies. If you go into your local terminal on your machine and enter the command 'g++' it should give you instructions on how to install it.

**Comment by daenney** [comment]
This usually stems from the fact that either Xcode or Xcode Command Line Tools aren't installed (on OS X).

**Comment by Zooce** [comment]
![failed_install](https://cloud.githubusercontent.com/assets/5490155/9796930/7aea8fa6-57ad-11e5-8ff4-d2948b0257c5.jpg)

Windows 7 x64
Atom 1.0.11

**Comment by jeremyramin** [comment]
@Zooce Sorry, there have been issues installing on Windows. It's a problem with one of the dependencies I use. I'll be sure to let you know when it's fixed.

**Comment by Zooce** [comment]
@jeremyramin Thanks, I appreciate it!

**Comment by jeremyramin** [comment]
The latest version [v0.4.0](https://atom.io/packages/terminal-plus) should fix this issue.
@Zooce It would be very helpful if you could give this latest update a try and let me know if it works on your system.

**Comment by Zooce** [comment]
@jeremyramin It's working great so far! Thanks for jumping on this issue so quickly!

**Comment by jeremyramin** [comment]
I'll ahead and close this issue since it appears to be fixed.
