### ISSUE TITLE
terminal task takes cursor focus

### ISSUE THREAD

**Issue by brbrr** [jeremyramin/terminal-plus#40]
While executing rspec tests (with logging in console) terminal taking focus from editor to terminal window,  so it's kinda hard to type with open terminal window.

**Comment by jeremyramin** [comment]
@brbrr I noticed that and I actually released a new version that should fix this issue. Are you on v0.9.1?

**Comment by brbrr** [comment]
Im on 0.9.1. Mac OS X, bash

**Comment by jeremyramin** [comment]
Well that is odd. That should have been fixed by v0.9.0. 
![example](https://cloud.githubusercontent.com/assets/3977054/10554330/4e6286ba-7417-11e5-9861-b7bb7b01117c.gif)

**Comment by jeremyramin** [comment]
Please update to the latest version (v0.10.0) and let me know if this issue is still there. This sounds like it would interrupt your workflow often so I would like to fix it as soon as possible.

**Comment by madranet** [comment]
I was seeing a similar thing with previous version, working with [Hugo](http://gohugo.io)'s 'watched folder' server settings. Every time I hit save, the cursor would jump into the terminal pane. 

I can confirm it's fixed [for me anyway] in 0,10,0

**Comment by brbrr** [comment]
Now it's definitely fixed for me. Thanks @jeremyramin

**Comment by jeremyramin** [comment]
@madranet Thank you for confirming that it has been fixed.
@brbrr You are welcome.

Thank you both for using Terminal-Plus.
