### ISSUE TITLE
it doesn't work on windows 10!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [jeremyramin/terminal-plus#407]
**can not input anything!**
![atom-terminal-error](https://cloud.githubusercontent.com/assets/18028768/20800628/1d6e7826-b821-11e6-9b11-9733dde5bc96.png)

**what should I do , may be some config ?**

**Comment by manis404** [comment]
same here. atom 1.12.6/win 10 x64

**Comment by pwcong** [comment]
me too.

**Comment by barbuslex** [comment]
Same issue on Windows 7 (x64). No output in terminal panel !

**Comment by clipsmm** [comment]
Any fix yet?
