### ISSUE TITLE
Resizing Broken in 0,10,0

### ISSUE THREAD

**Issue by madranet** [jeremyramin/terminal-plus#42]
Hi.

The latest version 0,10,0 has broken the ability to resize the terminal window by dragging.

*[OSX 10,9,5. Atom 1,0,190]*

**Comment by madranet** [comment]
UPDATE: This may be an intermittent or time-related problem. I had it happen  immediately after updating to 0,10,0 and it persisted through a reboot of Atom. However, when I returned to my open Atom window, after penning the above bug report, the terminal window was resizeable-by-dragging again. I quit Atom and re-opened it and the problem returned.

**Comment by madranet** [comment]
Back again!

I've sussed what the problem is: The terminal pane remains non-resizeable until after a terminal command has been issued. So, as it's a very minor cosmetic issue, I'll mark it as closed.

![atomterminal](https://cloud.githubusercontent.com/assets/669658/10558302/a6ca16aa-74c2-11e5-920e-ac9818aabbfb.gif)

**Comment by jeremyramin** [comment]
Actually, I would like to keep this open. I want you to be able to resize when ever you want. Thank you for the gif demonstrating the issue and the nice report.

**Comment by jeremyramin** [comment]
v0.10.1 should fix this. Please let me know if the issue still persists after the update.

**Comment by madranet** [comment]
Yep. Working fine now.

Cheers.
