### ISSUE TITLE
does not work 

### ISSUE THREAD

**Issue by ELHoussineT** [jeremyramin/terminal-plus#423]
when I open a new terminal, a terminal window slides up with a cursor in it, however there is nothing in it, no directory no user nothing.

**Comment by psnilesh** [comment]
Same here

**Comment by cmdillon** [comment]
...same here. terminal window slides up with a blinking cursor in it. nothing happens when i type in the terminal window.

**Comment by lekstonjm** [comment]
Same for me

**Comment by danielcondemarin** [comment]
+1

**Comment by ncoughlin** [comment]
+1

**Comment by hacu9** [comment]
+1

**Comment by stedmanhalliday** [comment]
+1

**Comment by ghost** [comment]
You should see [this](https://github.com/jeremyramin/terminal-plus/issues/402)
