### ISSUE TITLE
Terminal-Plus won't start anymore

### ISSUE THREAD

**Issue by ccpalmer** [jeremyramin/terminal-plus#424]
I initiate it with Command-Shift-T and the new window appears along with the status bar, but no shell gets started.  Typing in the window is ignored.

**Comment by kaushikchaubal** [comment]
+1 - happening to me too

**Comment by wiber** [comment]
+1

**Comment by Phylliade** [comment]
+1, exactly the same!

**Comment by kaushikchaubal** [comment]
I installed this and it worked: https://github.com/platformio/platformio-atom-ide-terminal

So good to have a terminal inside a text editor!

**Comment by SpaceWhite** [comment]
+1

**Comment by jbastias** [comment]
+1 :(

**Comment by nolanpro** [comment]
Seeing that this repo hasn't had any commits in a while maybe, as @kaushikchaubal mentioned, [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) is the way to go now. It seems to have active development. Anyone know of any other atom terminals in active development?

**Comment by nolanpro** [comment]
+1 Yeah @kaushikchaubal [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) appears to be in active development.

**Comment by gaelreyrol** [comment]
+1 :/

**Comment by hanibash** [comment]
@ccpalmer @kaushikchaubal @wiber @Phylliade @SpaceWhite @jbastias @nolanpro @Zevran

I would suggest [Termination](https://github.com/Fred-Barclay/Termination), which is a standalone package independent of an IDE and also seems to be more actively developed.

**Comment by peterlawless** [comment]
+1
