### ISSUE TITLE
unable input

### ISSUE THREAD

**Issue by myronliu347** [jeremyramin/terminal-plus#430]
I intalled terminal-plus, but can't input command, can`t run command,

**Comment by magicdawn** [comment]
same

**Comment by DamnedScholar** [comment]
This package hasn't been updated in a while. You might try `termination` or `platformio-ide-terminal`.

**Comment by magicdawn** [comment]
fixed via https://github.com/jeremyramin/terminal-plus/issues/402#issue-191791036

**Comment by myronliu347** [comment]
Thanks
