### ISSUE TITLE
Terminal does not present with prompt

### ISSUE THREAD

**Issue by salimnisha** [jeremyramin/terminal-plus#441]
Hi,

I installed Terminal Plus, but I see only a blank window with no prompt. And I'm unable to type anything in the window.

I'm using Mac OS X Yosemite, 10.10.5
![screenshot 2017-02-10 21 16 05](https://cloud.githubusercontent.com/assets/11134903/22832995/38fcb732-efd6-11e6-8322-7d033ef60e87.png)

**Comment by luismqueral** [comment]
+1, same issue here

**Comment by luismqueral** [comment]
@nocnoi Check out #433, looks like people are switching to `platformio-ide-terminal` (fork of terminal-plus) and works great.

**Comment by salimnisha** [comment]
@luismqueral Thank you. Tried that, didn't work.
