### ISSUE TITLE
Create custom Theme

### ISSUE THREAD

**Issue by Sam2304** [jeremyramin/terminal-plus#45]
I'd like to build a Monokai theme for Terminal-Plus but I'm not sure where to start, could you point me in the right direction?

I've created a `monokai.less` under the `themes` folder, and imported it in `themes.less`, but I don't seem to get an option from the settings pane in atom.

Also, where do I define text colours?  Do I just need to do that from the settings panel?

Thanks in advance, I love Terminal-Plus already, but would love to add a monokai theme to it!

UPDATE:  I've modified red.less to match the correct background and foreground colours, and used the colour swatches in the settings menu to more or less match my terminal profile.  the added monokai.less isn't showing up under the menu option though.

This will work for me for now, but of course I will likely lose my changes whenever I update your package

UPDATE AGAIN:

It helps if you read all of the readme, my apologies, followed your instructions and everything works like a charm, nice way of handling things!

(I'm pretty sure my atom instance is breaking when it comes to package settings at the moment, half my packages aren't reachable from within atom)

**Comment by jeremyramin** [comment]
@Sam2304 I'm glad you were able to find what you needed. On a side note, themes have to be added to the settings section of Terminal-Plus manually. Easier just to use the Atom Stylesheet.

At any rate, thank you for using Terminal-Plus. Closing this issue as it has been resolved.

**Comment by NicholasTD07** [comment]
@jeremyramin is there a way to add customized theme in the settings rather than modifying the package itself directly? I mean, if I modify the package itself to add a theme and if there's an update, it will override my modification, right?
