### ISSUE TITLE
[Mac] The terminal was freeze.

### ISSUE THREAD

**Issue by nico-arianto** [jeremyramin/terminal-plus#452]
Mac: Sierra (10.12.3)
Atom: 1.15.0 x64
Terminal-plus: 0.14.5 (with default Settings)

![image](https://cloud.githubusercontent.com/assets/6427889/23828684/c6fe4686-0714-11e7-9eed-ea31b80549e8.png)

**Comment by Fred-Barclay** [comment]
G'day @nico-arianto 

I've got a working fork that's being actively maintained: https://atom.io/packages/termination
`apm install termination`

There's  also https://atom.io/packages/platformio-ide-terminal which is another excellent terminal programme.

Cheers!

**Comment by nico-arianto** [comment]
Hi @Fred-Barclay,

OK, I will try to use `platformio-ide-terminal`.

Thanks.

**Comment by Fred-Barclay** [comment]
No worries mate. :)

**Comment by anacampesan** [comment]
had the same problem and termination seems to be working flawlessly, thank you @Fred-Barclay!
