### ISSUE TITLE
Process Titles gets stuck

### ISSUE THREAD

**Issue by JohnRoach** [jeremyramin/terminal-plus#46]
I was able to repeat this bug by doing the following:

1. Add three new tabs
2. While hovering on one of the terminal tabs wait for the title to show up.
3. Right click on the terminal and close it.
4. The title will remain and drive you mad... You will need to restart Atom.

Atom Version: 1.0.19
Plugin Version: 0.11.1
OS: Mac

![Image of the annoying SSH tip](https://www.evernote.com/l/AOd9OMKc_JdOgbf6jf9Nvv3gTVg8oIDI1HoB/image.png)

**Comment by jeremyramin** [comment]
@JohnRoach I realize that this can be quite irritating. I know it would bother me too. I'll take a look and try to have a fix out as soon as possible.

**Comment by jeremyramin** [comment]
As of v0.11.2, this issue should be fixed. Please let me know if you still see the tooltips after closing your terminal. If not, then we can close this.

**Comment by jeremyramin** [comment]
Closing this issue as of v0.11.2
