### ISSUE TITLE
unable to type

### ISSUE THREAD

**Issue by gforceg** [jeremyramin/terminal-plus#462]
I just installed atom and this terminal-plus (trying to migrate away from vscode).
The terminal contains a blinking cursor but nothing happens when I type.

**Comment by enokmadrid** [comment]
use platformio-ide-terminal instead
https://atom.io/packages/platformio-ide-terminal

**Comment by gforceg** [comment]
@enkolabs yeah I noticed that one works. I just get a ton of ugly error messages when it launches:
```
bash: module: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_module'
bash: scl: line 1: syntax error: unexpected end of file
bash: error importing function definition for `BASH_FUNC_scl'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
```
(I'm doing nodejs development but not IoT development, maybe that has something to do with it?)

Somebody should take over terminal-plus... I suppose terminal-plus must work for some people if it's the top 'terminal' plugin in atom... but somebody should take it over given that it obviously isn't being maintained.

Thanks again for the suggestion.

**Comment by gforceg** [comment]
This appears to be an issue w/ Fedora. I'm running Fedora 24 but the issue has been documented w/ Fedora 25.

When I start atom via bash I don't get the above scary lines. :)
Found this solution [here](https://github.com/platformio/platformio-atom-ide-terminal/issues/120#issuecomment-274756065)
