### ISSUE TITLE
Terminal not working on windows 7

### ISSUE THREAD

**Issue by cilsilver** [jeremyramin/terminal-plus#472]
Hello, Nice package. Having difficulty making this terminal-plus package work. I've tried uninstalling and re-install. Map the terminal to folders and yet still not working. Just  cursor blinking. Kindly assist
![terminal](https://cloud.githubusercontent.com/assets/5936073/25652485/5688b590-2fe0-11e7-83ee-1790bed8e735.jpg)

**Comment by Fred-Barclay** [comment]
G'day @cilsilver 
It seems that terminal-plus isn't being maintained any longer, and it doesn't work with the latest versions of Atom. I maintain a working fork if you'd like to try it.
`apm install termination`
https://atom.io/packages/termination

Another fine alternative is platformio-atom-ide-terminal.
