### ISSUE TITLE
When opening terminal, it shows blank. Just a black box without option to type

### ISSUE THREAD

**Issue by luisalvarado** [jeremyramin/terminal-plus#476]
Hi Jeremy, just trying out your terminal-plus but when I press CTRL + ~ it simply opens an empty black box with no cursor or something to start typing on it. Am using latest version of ATOM with latest version of yours.

**Comment by Hcaz528** [comment]
It's been working fine until today when I opened it up and got the same thing as luisalvarado

**Comment by cristianzamar** [comment]
fixed with #402
