### ISSUE TITLE
Doesn't work on the newest versions of Atom

### ISSUE THREAD

**Issue by estevE11** [jeremyramin/terminal-plus#488]
It just doesn't work.

**Comment by Fred-Barclay** [comment]
Hi @Coconaut11
terminal-plus doesn't seem to be maintained any longer. I maintain a working fork if you'd like to try that instead:
`apm install termination`

Another fine alternative is platformio-atom-ide-terminal.

**Comment by estevE11** [comment]
Thanks for replying!

De: Fred Barclay
Enviado: jueves, 15 de junio de 2017 21:04
Para: jeremyramin/terminal-plus
CC: Roger Esteve; Mention
Asunto: Re: [jeremyramin/terminal-plus] Doesn't work on the newest versionsof Atom (#488)

Hi @Coconaut11
terminal-plus doesn't seem to be maintained any longer. I maintain a working fork if you'd like to try that instead:
apm install termination
Another fine alternative is platformio-atom-ide-terminal.

**Comment by OussamaRomdhane** [comment]
@Fred-Barclay Thanks man you're a life saver
