### ISSUE TITLE
shortkey to send to terminal

### ISSUE THREAD

**Issue by jokedurnez** [jeremyramin/terminal-plus#5]
Is there an option to select a line of code and then send it to the active terminal with a shortkey (eg. Ctrl-Enter) instead of copy-pasting all the time?
That would be great :)

**Comment by jeremyramin** [comment]
That could be easily added. I'll see if I can get that in today in an update.

**Comment by jeremyramin** [comment]
@jokedurnez Would you prefer that your focus jumps to the terminal or stay in the text editor?
Example 1: You select text and press the shortkey then continue typing in the text editor.
Example 2: You select text and press the shortkey, then focus on the terminal if it is open.

**Comment by jokedurnez** [comment]
Wow I even have the choice !
I'm actually for a long time looking for a replacement for my favorite linux-editor kate and there it stays in the text editor.  This makes it easy to run only a few lines of code in a document.
And now that we're asking... Is it also possible to add an option that when you don't make a selection, the whole line where the cursor is, is sent to the terminal? And then afterwards the cursor jumps to the next line (like in Rstudio).  As such, pressing the shortkey consecutively, the code runs line per line.

Thanks so much! :)

**Comment by jeremyramin** [comment]
@jokedurnez Oh so the command should be run after being inserted? I have it working but it only inserts the text, it doesn't actually run the command.

**Comment by jokedurnez** [comment]
Running would be great.

**Comment by jeremyramin** [comment]
@jokedurnez Latest update has it. Give it a try and let me know if it works properly.

**Comment by jokedurnez** [comment]
Perfect! Thanks!
