### ISSUE TITLE
Is the terminal must use node@6.9 ?

### ISSUE THREAD

**Issue by Ding95** [jeremyramin/terminal-plus#505]
![qq 20170813091527](https://user-images.githubusercontent.com/12723947/29245290-21b9fef0-8008-11e7-8c9c-305c50e1f62f.png)
My system is win x64, use node@8..2.1 and npm@5.3.0. it install error. what should I do?

**Comment by synsh** [comment]
are you connected to the internet?
if not then make sure you are connected and try again

**Comment by Ding95** [comment]
I uninstall node and install node@6.9.5, then `rebuild package`, reload Atom, fixed!
