### ISSUE TITLE
Ctrl-Enter does not move text to console (having the issue on Windows 7 and Arch Linux)

### ISSUE THREAD

**Issue by JestonBlu** [jeremyramin/terminal-plus#52]
Highlighting text and hitting Ctrl-Enter moves the cursor to the next line without copying the text to the console. Selecting the text and using the command palate to send text to the console works though. I am seeing this issue on both a Windows 7 and Arch Linux install.

**Comment by Sam2304** [comment]
I believe this is a keybinding conflict. In my system, I get a conflict with ```editor:newline-below```, to turn that off you can edit your ```keymap.cson``` with the following:
```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-enter': 'unset!'
```

Which will disable the default keybinding, allowing Terminal-Plus to work as expected.  (I found this by turning on the Keybinding resolver '```Ctrl-.```' (fullstop) to identify what was conflicting, then going to the keybinding settings pane.

**Comment by JestonBlu** [comment]
Works perfectly, thanks!
