### ISSUE TITLE
Terminal Freezes on save file

### ISSUE THREAD

**Issue by JostCrow** [jeremyramin/terminal-plus#53]
When you have an active terminal and press control+s that the terminal does not response anymore.

Atom = 1.19.0
Terminal-plus = 0.12.1
Elementary os = 0.3.1

Also had this on ubuntu.

**Comment by jeremyramin** [comment]
@JostCrow I can't seem to be able to reproduce this in panel view or tab view. Which shell are you using?

**Comment by JostCrow** [comment]
I am using the default shell environment.

Sorry let me explain it better. It is not that I save a file. I accidentally save the terminal and then it won't respond anymore. That is how the terminal gets stuck. It completely freezes.

**Comment by jeremyramin** [comment]
That is interesting. If I make the terminal a tab view and save it, nothing happens on OS X. The terminal is still responsive. I will have to try this on my Ubuntu machine later.

**Comment by jeremyramin** [comment]
Fixed this in v0.12.5, please give it a try and let me know if it has been fixed. Please close this issue if it has been resolved.

**Comment by JostCrow** [comment]
This issue has been solved. Sorry for the late response.
