### ISSUE TITLE
Mac atom 1.25.0 X64 can not input anything

### ISSUE THREAD

**Issue by AzeWZ** [jeremyramin/terminal-plus#537]
Mac atom 1.25.0 X64 can not input anything

**Comment by 3dos** [comment]
Same here :/

**Comment by Davisa94** [comment]
Same issue but in windows ten

**Comment by uscitp-rsokolov** [comment]
+1 same issue here

**Comment by kunzeal** [comment]
+1

**Comment by bjce** [comment]
Same issue with atom 1.26.1
and I think this issue is a duplicate of that issue [https://github.com/jeremyramin/terminal-plus/issues/525](url)

**Comment by rythod** [comment]
+1 same issue.  really hope this is fixed soon, I love this IDE and terminal-plus is like the cherry on top

**Comment by Rhiana** [comment]
same issue, just installed it today on an up to date atom on osx and can't input anyhting

**Comment by Stedders** [comment]
+1 

Atom 1.26.1 x64, Mac OS 10.13.4.

**Comment by Liudongge** [comment]
+1
Atom 1.27.1 x64, Mac OS 10.13.3
after installed it today

**Comment by logopogo** [comment]
+1

**Comment by bjce** [comment]
I just find a possible alternative for people using `Hydrogen`. It's called `Hydrogen-launcher`. Here is the link:
[https://github.com/lgeiger/hydrogen-launcher](url)

I had to run the following lines in Terminal first (taken from this github page: [https://github.com/nteract/hydrogen/issues/243](url) 

$ sudo apt autoremove ipython
$ sudo apt install python-pip -y
$ pip install --upgrade pip

then, install ipython[notebook]

$ sudo pip install ipython[notebook]

But then it worked fine
