### ISSUE TITLE
terminal-plus is not working in atom, just cursor blinking - See attach screen shot

### ISSUE THREAD

**Issue by mrpatel15** [jeremyramin/terminal-plus#538]
[
<img width="827" alt="screen shot 2018-04-19 at 10 53 05 am" src="https://user-images.githubusercontent.com/11543074/39003180-ea9562e4-43bf-11e8-93e5-1b1dcff07496.png">
](url)

**Comment by mrpatel15** [comment]
please some can fix this issues, in it was really good feature. it was working before.

**Comment by elveskevtar** [comment]
Getting the same issue. Just installed it for the first time on Ubuntu 17.10. The newest version of Atom 1.26.0.

**Comment by jahshuah** [comment]
Ditto; I've got the same issue.

**Comment by dapepe** [comment]
Same here. Working on Mac High Sierra 10.13.4 + Atom 1.25.1

**Comment by Creative-Cats** [comment]
Same here...

**Comment by iuyoy** [comment]
Same issue.

**Comment by elveskevtar** [comment]
As many of you probably have figured out terminal-plus is no longer being maintained but still hasn't been taken off of atom packages. I found a very good alternative is https://atom.io/packages/terminal-tab

**Comment by mrpatel15** [comment]
this  package is working - "platformio-ide-terminal"
https://atom.io/packages/platformio-ide-terminal
