### ISSUE TITLE
Copy and paste does not work.

### ISSUE THREAD

**Issue by JostCrow** [jeremyramin/terminal-plus#54]
The commands don't work on my machine. I also tested it with the keybinding resolver open and it did not show the command when pasting in the terminal. It only showed that I pressed alt.

Atom = 1.19.0
Terminal-plus = 0.12.1
Elementary os = 0.3.1

Also had this on ubuntu.

**Comment by jeremyramin** [comment]
I just did a quick release that should fix this issue. Please take a look and see if you can paste now.

**Comment by jeremyramin** [comment]
Fixed as of v0.12.2

**Comment by JostCrow** [comment]
Thanks. This works perfect.
