### ISSUE TITLE
Support for multiple terminals

### ISSUE THREAD

**Issue by JestonBlu** [jeremyramin/terminal-plus#56]
It would be great if I could link to multiple terminals on Windows.  For Instance I have one terminal open running Git Bash, I would like to have another terminal that is the R Console. This already works on Linux since you can call both from the regular terminal, but not on Windows since you have to use the R console exe directly.

**Comment by jeremyramin** [comment]
I'll have to think of an easy way to implement this. Feel free to offer suggestions as to how you would like to be able to launch a terminal with a different shell.

**Comment by JestonBlu** [comment]
An implementation suggestion would be putting multiple paths to the console separated by a semicolon.. and then being able to right click the Add Terminal icon and choose from the list of consoles based on the executable name minus the extension.

This package is great by the way. I am almost to the point where it has completely replaced my need for other IDEs.

![path](https://cloud.githubusercontent.com/assets/3339909/10766758/f1a32f36-7ca6-11e5-8705-a287b2c4d5e8.png)

![menu](https://cloud.githubusercontent.com/assets/3339909/10766761/f4324fe8-7ca6-11e5-85db-bba10a828686.png)

**Comment by jeremyramin** [comment]
That could work. The first shell would be the default and then all shells would be listed in the right click menu. Right now, right click menus for the package are configured in a file. I will have to see if Atom will let me dynamically change the right click menu like this.
