### ISSUE TITLE
can't do anything at all

### ISSUE THREAD

**Issue by airmick** [jeremyramin/terminal-plus#578]
Using OS Ubuntu 18.04
atom version 1.44.0
nothing is working, just a white blinking in prompt

**Comment by ghost** [comment]
Nothing is happening in the shell 


is this a joke

**Comment by Theocrat** [comment]
I am using Pop!_OS 19.10. I am running Atom 1.42 on Electron 4.2.7, over Node 10.11; I installed this package with apm 2.4.3
As others before me have stated, the terminal doesn't do anything. It is simply a blinking cursor in a black background. I need bash to run inside atom at the very least, but this doesn't seem to be working. Is there some additional library or package I need to get this to work? I a going to install Jupyter Notebook to see if terminal.js is functioning in this system, but I really wonder if the terminal-plus project is functional yet.

**Comment by evilgeniusdev** [comment]
I am seeing the same behaviour.
OS: Mint 19.2
Atom: 1.44.0

**Comment by Theocrat** [comment]
Regarding the terminal-plus package inside the atom editor: I have
discovered that the atom-xterm package works better. It's a decent electron
implementation of the Bash shell.

**Comment by ju4nmg** [comment]
same happens 
OS: Linux Mint 19.2 Tina x86_64 
Atom: 1.42.0

**Comment by airmick** [comment]
Unless someone fix it, the best you should do is to install another package like https://atom.io/packages/atom-ide-terminal
It works just fine.
