### ISSUE TITLE
Unable to install the package in Atom (Atom version 1.56)

### ISSUE THREAD

**Issue by SanSri-at** [jeremyramin/terminal-plus#587]
Hey there, I am unable to install your package in the editor. (Other packages are installing fine.) Whenever I try an error message appears. I'll attach the output and the logs. 

![Screenshot 2021-04-14 205632](https://user-images.githubusercontent.com/82526998/114736919-27812e80-9d64-11eb-939e-e696b2af6df1.jpg)

Log file:  
[2021-04-14T15_16_05_606Z-debug.log](https://github.com/jeremyramin/terminal-plus/files/6311898/2021-04-14T15_16_05_606Z-debug.log)

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall terminal-plus and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by SanSri-at** [comment]
Okay, I'm new to this, so could you please tell me the difference between the two.

**Comment by UziTech** [comment]
terminus is an updated fork of terminal-plus so if you are used to the way terminal-plus works you might be more familiar with that one. x-terminal is a terminal that is meant to be used to have multiple terminals open at once.

Both have pros and cons. I would suggest trying each and seeing which one you like best.

**Comment by SanSri-at** [comment]
I see.
Thank you!
