### ISSUE TITLE
Install on version 1.58.0 broke

### ISSUE THREAD

**Issue by rvmilaan** [jeremyramin/terminal-plus#590]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/jeremyramin/pty.js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
**npm ERR! enoent This is related to npm not being able to find a file.**
npm ERR! enoent

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall terminal-plus and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by rvmilaan** [comment]
Thanks for the advise, I did, and works great, sorry for the inconvenience
