### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Keshav569** [jeremyramin/terminal-plus#591]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/jeremyramin/pty.js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bhoja\.atom\.apm\_logs\2021-09-09T03_21_23_441Z-debug.log

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall terminal-plus and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
