### ISSUE TITLE
login :  wrong option -- 'q'

### ISSUE THREAD

**Issue by miguelcarax** [jeremyramin/terminal-plus#6]
After open the terminal the next message shows:

"
login: wrong option -- 'q'
Use: login [-p] [-h <host>] [-H ]  [[-f] <username>]

Start a sesion in the system

cd ...
"

After that i'm not able to write if i click on it an error appear. I have default options

**Comment by jeremyramin** [comment]
@miguelcarax A new update just came out, please let me know if it fixes this issue.

**Comment by miguelcarax** [comment]
Now i'm able to write just a few seconds, after that i can't do anything, and the terminal don't accept the command. And the "clear" and "pwd" appear in terminal after the cwd.

**Comment by jeremyramin** [comment]
@miguelcarax I think I finally have it fixed. Please do give it one more try.

I'd like to apologize for all of the trouble, I haven't had a chance to test this on Linux until now. You are being very helpful and patient.

**Comment by miguelcarax** [comment]
It works now! Just one last think, it's possible to terminal to close when i type "exit", it only show "logout" but don't close, thank!

**Comment by jeremyramin** [comment]
@miguelcarax I can add that as an option in the settings. It used to close on exit but I had to remove that so we could see what the output from your terminal was.

**Comment by jeremyramin** [comment]
@miguelcarax The latest update should have `Close Terminal on Exit` in the settings. If you enable it, it should do what you requested.

**Comment by miguelcarax** [comment]
It works perfectly! So many thx! :)

**Comment by jeremyramin** [comment]
@miguelcarax Thank you for being patient with me while fixing the issue.
