### ISSUE TITLE
Cant send large selected text to the terminal

### ISSUE THREAD

**Issue by JestonBlu** [jeremyramin/terminal-plus#61]
I have noticed when selecting a large amount of text that scrolls off the page that I am unable to send that selected text to the terminal with either Ctrl-Enter or selecting Insert Text from the command palette.

It seems to work fine as long as I dont have to scroll to select what I want to send.

**Comment by jeremyramin** [comment]
@JestonBlu Sorry for the delay. I will test this and get back to you.

**Comment by jeremyramin** [comment]
I just had a chance to test this and I experienced no issues inserting a large selection of text that scrolls down the text editor. I selected multiple lines and then pressed `ctrl+enter` and all lines were inserted into the terminal. What exactly is happening for you when you try to insert this large amount of text?

**Comment by JestonBlu** [comment]
I did some additional testing and I noticed that the insert function did work correctly when I tried to insert 50 or so lines of ls with scrolling.  What I am specifically using it for is to send sql to the terminal, so just one long query as opposed several complete commands.  It seems to work fine as long as my query does not go off screen and I dont have to scroll to capture all of the text, but as soon as I do i get no response to Ctrl-Enter or Insert Selected Text from the command palette.

**Comment by JestonBlu** [comment]
I had a coworker test this and he is seeing the same behavior

**Comment by jeremyramin** [comment]
So one really long command breaks it. I will have to test this and get back to you.

**Comment by jeremyramin** [comment]
I was able to insert one very long chain of `ls && ls && ls...` that scrolled far to the right successfully. It is hard to test since I do not have the exact setup that is giving you issues. The insert selected text makes no distinction over what text is being selected so there is no reason for the SQL not to insert. If this makes a difference to your input, `Insert-Selected-Text` appends the appropriate end-of-line character to your selection when it inputs it into your terminal.

**Comment by JestonBlu** [comment]
Thanks for looking into it. Ill see if I can create a reproducible example for you on Monday.

**Comment by JestonBlu** [comment]
Here is an example of one of the long queries I am trying to send to the console which involves me scrolling to capture it all. In my specific setup, I am using Git Bash as my terminal on Windows 7(I tried with powershell and got the same results) . I also have `Run Inserted Text` unchecked since I need it to all be executed as one statement.

```sql
with last_12 as(
    select
        commodity,
        round(sum(exposure_weight)) as "last_12"
    from fbbi_prodtn.cmdty_final
    where period between add_months(trunc(sysdate, 'MM'), -12)
        and add_months(trunc(sysdate, 'MM'), -1)
    group by commodity
    order by sum(exposure_weight) desc),
    -- Last 13-24 Months
    last_12_24 as (
    select
        commodity,
        round(sum(exposure_weight)) as "last_12_24"
    from fbbi_prodtn.cmdty_final
    where period between add_months(trunc(sysdate, 'MM'),-24)
        and add_months(trunc(sysdate, 'MM'), -13)
    group by commodity
    order by sum(exposure_weight) desc),
    -- Last 25-36 Months
    last_24_36 as (
    select /*+ parallel */
        commodity,
        round(sum(exposure_weight)) as "last_24_36"
    from fbbi_prodtn.cmdty_final
    where period between add_months(trunc(sysdate, 'MM'),-36)
        and add_months(trunc(sysdate, 'MM'), -25)
    group by commodity
    order by sum(exposure_weight) desc),
    -- Next 12 Months
    next_12 as (
    select
        commodity,
        round(sum(exposure_weight)) as "next_12"
    from fbbi_prodtn.cmdty_final
    where period between trunc(sysdate, 'MM')
        and add_months(trunc(sysdate, 'MM'), 11)
    group by commodity
    order by sum(exposure_weight) desc)
    -- put it all together
    select
        last_24_36.commodity,
        last_24_36."last_24_36",
        last_12_24."last_12_24",
        last_12."last_12",
        next_12."next_12"
    from last_24_36
    inner join last_12_24 on (last_24_36.commodity = last_12_24.commodity)
    inner join last_12 on (last_24_36.commodity = last_12.commodity)
    inner join next_12 on (last_24_36.commodity = next_12.commodity)
    order by "last_12" desc;
```

**Comment by jeremyramin** [comment]
I will have to give this a try. Sorry for the late reply, this is a busy week for me.

**Comment by jeremyramin** [comment]
Please try sending the long message to the terminal. v0.13.1 has an update that might fix the issue.

**Comment by JestonBlu** [comment]
I gave it a shot, but it didn't work.  I also tried copying the text to the clipboard and pasting it into the terminal, but that didn't work either.  I was able to copy and paste to a different window to check that I was copying properly.  I wonder is the issue that terminal plus isnt able to copy all of the selected text?

**Comment by jeremyramin** [comment]
Tests on both Windows 8.1 and OS X show that I could both insert and paste the long query into the terminal. On OS X, I was using zsh. On Windows 8.1, I was using the default (powershell). In both instances I could:

Highlight the query and use the `insert selected text` command to insert the text.
Copy the query and paste it in.

I don't have anything that can actually parse the SQL query, but at the very least powershell in Windows received the entirety of the long query. We will have to see what is different about your environment that prevents this from working.

**Note:** You might want to try pasting via the right click menu for Windows if `alt-v` does not work.

**Comment by JestonBlu** [comment]
Thanks for looking into it.  For small text I am able to highlight, copy to the clipboard and right click paste into the terminal, but I get the same no response when I select the larger text. Not sure where to go from here.  Let me know if you want me to close the ticket.

**Comment by jeremyramin** [comment]
Let's not close this just yet. I will continue to test this on other machines and get back to you as soon as I can.
