### ISSUE TITLE
Add support for syntax highlighting

### ISSUE THREAD

**Issue by JestonBlu** [jeremyramin/terminal-plus#63]
I don't know if this is possible, but it would be nice to be able to set each terminal to a specific syntax highlighting scheme. Also maybe an option to make syntax highlighting dynamic based on the extension of the script that the command was sent from.

**Comment by jeremyramin** [comment]
The highlighting would have to be done by the command that is displaying output on the terminal. That command would have to send color escape sequences between the syntax in the output to highlight it. Not exactly feasible to implement syntax highlighting directly into the terminal emulator. Sorry about this.
