### ISSUE TITLE
Copy/paste with a keyboard shortcut

### ISSUE THREAD

**Issue by nunocastromartins** [jeremyramin/terminal-plus#68]
In Linux it is usually possible to copy/paste text from/into the terminal by using the keyboard shortcut `Ctrl + Shift + C/V`.

I wonder if it would be possible to add this feature.

**Comment by jeremyramin** [comment]
Fixed this just now in my dependency. In the next update you should be able to bind `terminal-plus:paste` and `terminal-plus:copy`.

**Comment by jeremyramin** [comment]
Fixed as of v0.12.4. Please try mapping to `Ctrl-shift-v` now and see if it works.
