### ISSUE TITLE
incompatible package:  Cannot find module '/home/huaraz2/.atom/packages/terminal-plus/node_modules/pty.js/build'

### ISSUE THREAD

**Issue by Huaraz2** [jeremyramin/terminal-plus#71]
This message comes up everytime I open atom in dev mode and occasionally when i open it in normal mode.  I have the latest stable release for atom and the also have semingly all of the dependancies i need.  It is able to fix it in both normal and dev mode but when i restart it in dev mode it comes up again as an incompatible package.  It works fine when i reload atom in normal mode after it has fixed it.
![incompatable package for terminal-plus](https://cloud.githubusercontent.com/assets/8998661/10882435/99aae826-8162-11e5-9553-c2995b06af22.png)

**Comment by jeremyramin** [comment]
I will have to test this myself and get back to you. Thank you for bringing this to my attention.

**Comment by jeremyramin** [comment]
This should be fixed as of v0.13.1. You might need to uninstall and then reinstall Terminal-Plus to reset Atom's cache for the package.

**Comment by Huaraz2** [comment]
Thanks @jeremyramin have updated to v0.13.1 and it now works great in both dev and normal mode.  Didn't need to uninstall and reinstall it either.  
This is an AWESOME package by the way :+1:  :smiling_imp:

**Comment by jeremyramin** [comment]
That is good to hear. Sorry for the delay, took me a while to find the time to test it.

>This is an AWESOME package by the way :+1:  :smiling_imp:

Thank you, that means a lot.
