### ISSUE TITLE
How do you increase the font size?

### ISSUE THREAD

**Issue by eburnette** [jeremyramin/terminal-plus#73]
I tried editing the style sheet but font-size had no effect. Also Ctrl-Mousewheel doesn't work like it does in a normal Atom edit window. So how do you make the font bigger in the terminal window?

**Comment by nunocastromartins** [comment]
I believe you can use `!important` in your style sheet to override the default font size. :-)
e.g.: `font-size: 24px !important;`

**Comment by eburnette** [comment]
That didn't work.

.terminal-plus .xterm {
  font-size: 100pt !important;
}

**Comment by nunocastromartins** [comment]
Try using `.terminal-plus .terminal` as a selector. Works for me.

**Comment by eburnette** [comment]
That worked. Thanks. 

I got ".terminal-plus .xterm" from your doc under "Themes". Using .xterm works for background-color but not for font-size. I tried background-color with .terminal and that did not work, but if I added !important then that worked. It's a little confusing but not a big deal.

I've tried several terminal plugins on Windows and yours works the best. Keep up the good work.

**Comment by nunocastromartins** [comment]
I'm glad I could help, but I'm not the owner of this plugin! :smile:
Just someone that agrees with you in that this one works the best.

**Comment by jeremyramin** [comment]
@eburnette Hi there, original developer here. Sorry for the late reply, it has been a really busy week.

As for setting the font size, the Terminal-Plus settings has some styling options (including setting the font size) that you can tinker with:

![screen shot 2015-11-06 at 11 56 15 am](https://cloud.githubusercontent.com/assets/3977054/11007238/68400640-847d-11e5-91b5-5022618b12d7.png)
*Note: There are even more options to mess with than pictured here.*

But setting the stylesheet works as well.

@nunocastromartins Thank you for answering his question while I was out!
