### ISSUE TITLE
Issue with terminal tooltips

### ISSUE THREAD

**Issue by nunocastromartins** [jeremyramin/terminal-plus#75]
There seems to be some sort of glitch with the terminal tooltips:

![Tooltip issue](https://cloud.githubusercontent.com/assets/8314616/11008656/ee22ec68-84c9-11e5-9299-2f77f68f1823.png)

As you can see, it looks like there are two tooltips, one on top of the other.
I believe that the one on the back says `/bin/bash`.

This wasn't very noticeable with the theme I was previously using (although still possible to notice), but with this one it's easy to see.

Steps to reproduce:

1. Create new terminal (tooltip will say `/bin/bash`, at least in my case)
2. Run some program through the terminal (e.g. `node` or `ping` - helps if the name of the program is small :smile:)

**Comment by jeremyramin** [comment]
Expect a fix in the next release.

**Comment by jeremyramin** [comment]
Fixed as of v0.13.1. Should improve terminal titles as well.
