### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by MocanuMarius** [jeremyramin/terminal-plus#78]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'focus' of undefined

```
At /home/sublm/.atom/packages/terminal-plus/lib/view.coffee:567

TypeError: Cannot read property 'focus' of undefined
  at TerminalPlusView.module.exports.TerminalPlusView.focusTerminal (/home/sublm/.atom/packages/terminal-plus/lib/view.coffee:370:20)
  at TerminalPlusView.focusTerminal (/home/sublm/.atom/packages/terminal-plus/lib/view.coffee:1:1)
  at TerminalPlusView.module.exports.TerminalPlusView.focus (/home/sublm/.atom/packages/terminal-plus/lib/view.coffee:374:5)
  at HTMLDivElement.<anonymous> (/home/sublm/.atom/packages/terminal-plus/lib/view.coffee:1:1)
  at HTMLDivElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  8x -0:52.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:50.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:49.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.7.0 enhanced-tabs:toggle (atom-text-editor.editor)
     -0:48.5.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:48.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:46.9.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:41.4.0 enhanced-tabs:toggle (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:38.5.0 enhanced-tabs:toggle (atom-text-editor.editor.is-focused)
     -0:35.7.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:34.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11 terminal-plus:toggle (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 terminal-plus:toggle (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
coffee-compile, v0.19.2
coffee-navigator, v0.0.16
coffee-refactor, v0.7.0
color-picker, v2.0.13
fancy-bracket-matcher, v0.4.1
file-icons, v1.6.11
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.10.0
linter-coffee-variables, v0.4.1
linter-coffeescript, v1.0.0
minimap, v4.16.0
node-debugger, v1.1.9
nodejs-snippets, v1.0.3
refactor, v0.6.0
terminal-plus, v0.14.0
tree-view-git-branch, v0.0.6

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
It would be very helpful if you could tell me what settings you have enabled in the Terminal-Plus settings.

**Comment by MocanuMarius** [comment]
After i've restarted atom it seemed to work...

**Comment by jeremyramin** [comment]
The update might have caused the issue. Either way I added a check for an undefined terminal so this issue should be fixed as of v0.14.1.

**Comment by laxminarayanmishra** [comment]
Hi 
I am using my custom GUI extension named snippet extension.

Its a aspx page wherei have used Button control of cc:tridionmanager .

It is working fine but when I am clcking on close button, I am getting below error.

Uncaught TypeError: Cannot read property 'focus' of undefinedTridion.Controls.ModalIframePopup.focus @ coreresource_v8.1.0.194.12_.js?sav=1&cnt=core:128Tridion.Controls.BaseModalPopup._keepFocus @ coreresource_v8.1.0.194.12_.js?sav=1&cnt=core:126Tridion.Controls.PopupManager._handleOverlayElementClick @ coreresource_v8.1.0.194.12_.js?sav=1&cnt=core:130(anonymous function) @ coreresource_v8.1.0.194.12_.js?sav=1&cnt=core:5executeListener @ coreresource_v8.1.0.194.12_.js?sav=1&cnt=core:22i @ coreresource_v8.1.0.194.12_.js?sav=1&cnt=core:22


COuld you please let me know what is causing this issue. THnaks in advance

**Comment by laxminarayanmishra** [comment]
Uncaught TypeError: Cannot read property 'focus' of undefined  @.......
Tridion.Controls.ModalIframePopup.focus @ …….
Tridion.Controls.BaseModalPopup._keepFocus
Tridion.Controls.PopupManager._handleOverlayElementClick
(anonymous function)
executeListener
