### ISSUE TITLE
zsh: command not found

### ISSUE THREAD

**Issue by siklodi-mariusz** [jeremyramin/terminal-plus#8]
I'm trying to use this terminal in a Rails project and when I run any command like:

bundle exec rails server
bundle install

I get somethin like:
zsh: command not found: bundle

If I run rails server without bundler I get
/usr/bin/env: ruby: No such file or directory

As you can see I also use oh-my-zsh.

Any ideas?

**Comment by jeremyramin** [comment]
@siklodi-mariusz Some questions I have so I can figure out why this is happening:
1. What OS are you operating from?
2. Which shell are you currently using? (You can check by going into the package settings and seeing what the default is for `Shell Override`)

**Comment by siklodi-mariusz** [comment]
Sorry ,I forgot about the OS. I use Ubuntu 14.04
And yes ```bundle``` works in the system's terminal, I also have the zsh plugin for ```bundler``` which has some aliases that make ```bundle install``` become ```bi``` and so on. In my system's terminal bought work.

**Comment by jeremyramin** [comment]
So your aliases aren't appearing either? May I ask which zsh profile file
you are putting your alias settings in?

**Comment by siklodi-mariusz** [comment]
The plugins are configured in ~/.zshrc. I don't think the plugins are the problem because I also have plugins for ```git``` and ```rvm``` and they work.

**Comment by jeremyramin** [comment]
If you enter the `alias` command, do you see your aliases? It might not be
loading your zsh profile.

**Comment by siklodi-mariusz** [comment]
Yes I do see them, ```alias | grep bundle``` returns this plus other commands.
```bcn='bundle clean'```
```be='bundle exec'```
```bl='bundle list'```
```bo='bundle open'```
```bp='bundle package'```
```bu='bundle update'```

**Comment by jeremyramin** [comment]
In your regular terminal if you type `which bundle`, what location does it give you?
You can check the path variable (`echo $PATH`) in the Terminal-Plus terminal to see if that path is there.

**Comment by siklodi-mariusz** [comment]
Yep, this is the problem. When I run ```which bundle``` in my system's terminal I get: **/home/mariusz/.rvm/gems/ruby-2.2.2/bin/bundle** and the path is also present in $PATH. 
The thing that this changes when I change the ruby version an gemset with rvm.
In Terminal-Plus when I ```echo $PATH``` I don't have that path, I have this:
**/home/mariusz/npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mariusz/.rvm/bin**

**Comment by jeremyramin** [comment]
Okay so it loads the aliases but it isn't resolving the PATH properly. In Terminal-Plus can you run the command `zsh --login`. If that doesn't work then `zsh -l` might be it. That would place you in a new zsh shell. Check PATH once more in this new shell instance please.

**Comment by siklodi-mariusz** [comment]
Yep, this works.

**Comment by jeremyramin** [comment]
So this fixes the issue? Fantastic. Did you end up using `--login` or `-l`?

**Comment by siklodi-mariusz** [comment]
Yes it works all the comands seem to work fine. I used ```--login```
So is this is? I just have to run this command after I open a termina-plus?
If I remember right I saw something in the settings of Terminal-plus an option to run a command when an instance was open but I can't find it now. It was removed?

**Comment by jeremyramin** [comment]
The option to add `Shell Arguments` should be there. I was actually going to include the command myself because it should do this by default.

**Comment by siklodi-mariusz** [comment]
Ok, something else must be wrong because the only options I have are the colors.

**Comment by jeremyramin** [comment]
Oh, that's not good. What version of atom are you on?

**Comment by siklodi-mariusz** [comment]
1.0.2

**Comment by jeremyramin** [comment]
Ah yes. There was a bug in atom for settings configurations like in Terminal-Plus. It was fixed by Atom version 1.0.8. Updating will fix the settings issue.

**Comment by siklodi-mariusz** [comment]
Ok, great. Thank you very much for your help and for this great terminal package!

**Comment by jeremyramin** [comment]
Thank you for being patient with me while working out the issues. I hope you continue to enjoy the package.

**Comment by jeremyramin** [comment]
c44b6622bf76db7bda026831d0e2c35d5e7bfc54 fixes this issue.
Released in v0.4.1
