### ISSUE TITLE
Loses focus when switching from another window

### ISSUE THREAD

**Issue by tonatiuh** [jeremyramin/terminal-plus#81]
OS: OS X 10.11.1 
Atom version: 1.1.0
Terminal-plus version: 0.14.0
Shell: fish 2.20

The bug:
Given I have a terminal-plus terminal opened and focused
when I switch to another window using cmd+tab
and I switch back to atom
then the focus is lost (I type in the keyboard and only the first character appears)

**Comment by jeremyramin** [comment]
Fixed this. Expect it to work in the next release. You will have to restart Atom to see the change take effect.

**Comment by tonatiuh** [comment]
Do you mean release 15? Do you have an idea of when to launch it?

**Comment by tonatiuh** [comment]
Thanks for this good Atom package btw.

**Comment by jeremyramin** [comment]
It will be in a patch (0.14.1) sometime soon after I fix several of the other issues that came up today.

**Comment by jeremyramin** [comment]
Fixed as of v0.14.1
