### ISSUE TITLE
not compatible with atom v1.2.0

### ISSUE THREAD

**Issue by kambing86** [jeremyramin/terminal-plus#83]
error occur, please check

**Comment by jeremyramin** [comment]
Yes, Atom 1.2.0 will break Terminal-Plus unless you have the proper dependencies for [node-gyp](https://github.com/nodejs/node-gyp#installation). If you do not mind waiting, I should have a new release with updated binaries soon.

**Comment by williamokano** [comment]
No error here but the terminal shows up but never really open for tipying my commands.

Trying this node-gyp

**Comment by jeremyramin** [comment]
v0.14.1 has the updated binaries for Atom 1.2.0
