### ISSUE TITLE
Text shadow

### ISSUE THREAD

**Issue by daducci** [jeremyramin/terminal-plus#84]
Hi,
no matter what terminal theme I choose, a shadow always appear around the text.
Is is something that can be removed? I'm on OSX. I don't see such text shadow in system shells such as Terminal.app or iTerm2.app.
Thanks!

**Comment by jeremyramin** [comment]
@daducci Can you please provide a screen shot? I do not apply a text shadow to the text at any point.

**Comment by daducci** [comment]
Sure!
<img width="569" alt="shadow" src="https://cloud.githubusercontent.com/assets/369680/11155668/eb2ab2a2-8a14-11e5-97c1-de0d649d9e01.png">
Perhaps it's a stupid thing, in case I apologize. I started yesterday to play with Atom plugins and I'm trying to implement a sort of cell-mode like in Matlab. If you want, I can share the code for that..

**Comment by jeremyramin** [comment]
Well, that is definitely a text shadow. Do you see this in your default shell? It seems you are using something else.

**Comment by daducci** [comment]
No, it appears only within the term in Atom. Here is a screenshot from the other two system terminals on OSX: iTerm2.app (left) and Terminal.app (right):
<img width="936" alt="iterm_and_terminal" src="https://cloud.githubusercontent.com/assets/369680/11155881/63baa41a-8a16-11e5-9565-747fff1e4d88.png">

**Comment by jeremyramin** [comment]
May I ask what theme you are using for Atom?

**Comment by daducci** [comment]
It was Atom Light, and indeed that was the problem generating the shadow.. Sorry for that, I didn't know it might related to the main theme..
Thanks a lot!

By the way, are you interested in having a "cell mode" into your package? I use it mainly to inetract with ipython, but it is customizable.

**Comment by jeremyramin** [comment]
No problem, glad you were able to solve the issue.

It sounds like a great addition but I do not think I will be able to get to it anytime soon since there are a lot of fixes and enhancements that I have to get to.
