### ISSUE TITLE
Feature: navigation within input line

### ISSUE THREAD

**Issue by brbrr** [jeremyramin/terminal-plus#90]
There would be nice to have navigation functionality such as in mac terminal app:
1. [alt] + [left]/[right] - For moving to beginning of previous word/end of next word. useful when editing come copypasted commands
2. [alt] + mouse click - For placing cursor where mouse was clicked.

**Comment by jeremyramin** [comment]
Added as of v0.14.5. Review the changes and let me know if your issue has been properly fixed. If your issue has been resolved, please close this issue thread.

**Comment by brbrr** [comment]
awesome! thanks :+1:
