### ISSUE TITLE
Tabs are displayed weird.

### ISSUE THREAD

**Issue by JostCrow** [jeremyramin/terminal-plus#91]
There is a problem with the Tabs that they do not align correct. 

The steps:
1. Open a terminal as a tab.
2. Open a second ternimal (not as a tab).
3. switch between them.
4. Should turn out as the image below.

![screenshot from 2015-11-16 11 14 50](https://cloud.githubusercontent.com/assets/390575/11179470/bfbcbbc4-8c53-11e5-9ea5-81ba9130aabd.png)

**Comment by jeremyramin** [comment]
I was not able to reproduce this issue. If you could provide an animation or more information, that would be great.

**Comment by JostCrow** [comment]
I will make an animation tomorrow at work.

On Mon, 16 Nov 2015 22:33 Jeremy Ebneyamin <notifications@github.com> wrote:

> I was not able to reproduce this issue. If you could provide an animation
> or more information, that would be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeremyramin/terminal-plus/issues/91#issuecomment-157177384>
> .
>
-- 

Jorik Kraaikamp

**Comment by JostCrow** [comment]
Is there a way to send the screen recording to you?

**Comment by jeremyramin** [comment]
You can attach files here on Github I believe. The best would be a gif file since Github would just display it here without me having to download it.

**Comment by JostCrow** [comment]
I am working on it

**Comment by JostCrow** [comment]
![out2](https://cloud.githubusercontent.com/assets/390575/11241804/08052dca-8dfe-11e5-9b72-7db647386349.gif)

**Comment by jeremyramin** [comment]
Should be fixed by v0.14.4. Please remember to close this thread if your issue has been resolved.

**Comment by JostCrow** [comment]
Thanks it seems to work perfectly
