### ISSUE TITLE
win10 Threshold 2, couldn't run msys2 zsh

### ISSUE THREAD

**Issue by yzhen123** [jeremyramin/terminal-plus#92]
it's a really strange  problem that I couldn't run zsh, because the cmd  console shows   memory isn't enough or couldn't  allocate memory  when I try  to  run  zsh/bash/sh(msys2). My laptop was  left in my company, I'll  upload the screen  captures tomorrow.

**Comment by jeremyramin** [comment]
I will give this a try on my Windows machine sometime. Thanks for the report!

**Comment by yzhen123** [comment]
![image](https://cloud.githubusercontent.com/assets/5233940/11199583/be31179e-8d09-11e5-9e2b-023f7e515093.png)

The Chinese charactors above means the memory is not enough, couldn't handle this command.Then I try to run zsh, here are the output.

![image](https://cloud.githubusercontent.com/assets/5233940/11199586/c88cb072-8d09-11e5-9884-24176d38910f.png)


But if I run zsh on my cmd console directly, here are no problem. 
![image](https://cloud.githubusercontent.com/assets/5233940/11199654/7102a360-8d0a-11e5-87a5-3684e595b588.png)

**Comment by yzhen123** [comment]
It's really luck that I find the reason this morning, it seems that it's caused by forking a 64-bit subprocess from a 32-bit cmd(or win-pty?), check this <http://sourceforge.net/p/msys2/tickets/208/> and I find a solution: 
![image](https://cloud.githubusercontent.com/assets/5233940/11201299/cd93c8ae-8d17-11e5-9a1b-704c316c3903.png)

**Comment by jeremyramin** [comment]
@yzhen123 I am glad you were able to find a solution to this.

**Comment by yzhen123** [comment]
@jeremyramin well, I have to say it's hard to find a solution in windows (or usually don't even exist), but since I'm going to change my laptop to a macbook, hope there would be less time to face these kind of question.
