### ISSUE TITLE
Option to "run script" or "run selection"

### ISSUE THREAD

**Issue by pcgeek86** [jeremyramin/terminal-plus#93]
It would be really helpful to be able to hit `F5` to "run script" or `F8` to "run selection" from the Atom Editor window. I didn't initially see this option, when I looked for it, but it would be great to see some integration here. Does it already exist?

**EDIT**: I just found the `CTRL + Enter` shortcut. However, this has a few pitfalls:

1. It doesn't set focus to the terminal.
2. It requires the user to select text (should be optional).
3. It doesn't immediately invoke the command (unless there's a carriage return at the end of line).

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by jeremyramin** [comment]
>It doesn't set focus to the terminal.

This is for the case where users want to just run a command and see its output without focusing on the terminal.

>It requires the user to select text (should be optional).

If nothing is selected, it should insert the entire line that your cursor is at.

>It doesn't immediately invoke the command (unless there's a carriage return at the end of line).

That requires you toggle the option `Run Inserted Text` from the Terminal-Plus settings.

**Comment by jeremyramin** [comment]
Please close this thread if your issue has been resolved.
