### ISSUE TITLE
Run terminal-plus in separate window

### ISSUE THREAD

**Issue by pcgeek86** [jeremyramin/terminal-plus#94]
I'd like to run `terminal-plus` in a separate window in Atom, so I can move it to a separate monitor, and have more control over the window's position. Is this possible in the Atom framework?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by jeremyramin** [comment]
You can achieve this by doing the following:
1. Open a new window in Atom.
2. Open a new terminal in that new window.
3. Drag that terminal's status icon (the little icon in the status bar at the bottom of the window) up to the tab-bar area in the Atom window. It should now occupy the full Atom window as a tab.

**Note:** The tab view is experimental but should be functional.

**Comment by jeremyramin** [comment]
Did this work for you?

**Comment by pcgeek86** [comment]
@jeremyramin Yes this worked! Thank you. I wonder if it's possible to do "New Terminal Plus Tab" in Atom somehow.

Cheers,
Trevor Sullivan
